### ISSUE TITLE
Run spec does not work if the spec file has a comma in it

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/Intellij-Plugin#101]
I have found a bug where a spec does not run in Intellij IDEA if there is a comma in the file name.

To reproduce:

 1. Create spec file with a comma (e.g. "Hello,world.spec")
 2. Right click on the file in IDEA and choose "Run", then choose the spec

The following output occurs:

    "C:\Program Files\Gauge\bin\gauge.exe" --simple-console "C:/dev/apps/AthenaBrowser/Gauge Hierarchy/Foo/specs/hello" world.spec
    11:21:06.442 [INFO] No specifications found.

Note that the command ended with `hello" world.spec` instead of `hello,world.spec"`

If I rename the file to remove the comma, it works correctly.

**Comment by mahendrakariya** [comment]
Looked further into the issue. Here's what is happening.

In IntelliJ run configuration, users can pass multiple specs file to run. The files should be separated by a comma. Gauge plugin gets the file names by splitting the string at every occurrence of comma character.

So if a filename has a comma in it, Gauge will split it into two. That's the reason for the behavior mentioned by @Thunderforge above.

**A possible fix**

One of the ways to fix this will be change the character from comma to something else. The implications will be that it will be a breaking change. After users update the Gauge plugin, they will change all their run configurations with multiple files.

**Comment by Thunderforge** [comment]
@mahendrakariya I think we should do what JUnit does and use `||` as the delimiter.

![junit intellij idea](https://cloud.githubusercontent.com/assets/6200170/14930708/a6c437c8-0e2b-11e6-9acd-8a841bdcae4f.png)

File names on Windows do not allow the `|` character. It looks like OS X and Linux allow it. Probably worth running JUnit on a Mac to make sure it's the same there.

**Comment by mahendrakariya** [comment]
We have changed the delimiter to `||`. The fix should be available in nightly >= 2016-06-09.
