### ISSUE TITLE
Gauge plugin overrides find usages for java source code

### ISSUE THREAD

**Issue by nicity** [getgauge/Intellij-Plugin#102]
After installing Gauge 0.0.14 our IntelliJ IDEA users experience problem with Find Usages inside java source code. Specifically for simple project https://youtrack.jetbrains.com/issue/IDEA-144659#comment=27-1133264 find usages stopped to suggest to search usages for the interface's base method

**Comment by nicity** [comment]
CustomFindUsagesHandlerFactory.canFindUsages overrides handling of java method (PsiMethod) by JavaFindUsagesHandlerFactory

**Comment by mahendrakariya** [comment]
Thanks for reporting this issue. We will take a look at it.

**Comment by kashishm** [comment]
We have released [Gauge-Intellij 0.0.15](https://github.com/getgauge/Intellij-Plugin/releases/tag/v0.0.15) with the fix. Feel free to reopen the issue if you see the same behaviour in the new version.
