### ISSUE TITLE
Intellij IDEA freezes when renaming a concept in a project with many specs

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/Intellij-Plugin#107]
I had Intellij IDEA  freeze while renaming a concept. The steps I took were as follows:
1. Open a spec containing the concept
2. Right-click on the concept
3. Go to Refactor -> Rename...
4. Type in a new name and click "OK"

This results in a freeze in our project with 361 specs. I tried waiting it out twice before killing Intelij IDEA through the task manager, the first time for 8 minutes and the second time for 21 minutes. As soon as the app was force-quit, the `api.log` file was added to with the refactor result. Here is the log (data in `{}` is a placeholder for sensitive data):

```
14:49:02.659 [INFO] Watching directory: {Gauge directory}\specs
14:49:02.667 [INFO] Initializing concepts cache with 11 concepts
14:49:03.265 [INFO] Watching directory: {Gauge directory}\specs\concepts
14:49:03.458 [INFO] Initializing specs cache with 361 specs
14:49:09.271 [INFO] Initializing steps cache with 8077 steps
15:10:28.715 [INFO] Refactoring result from gauge:
Specs changed        : [{list of 73 specs}]
Concepts changed     : [{list of 1 concept}]
Source files changed : []
Warnings             : [Table not associated with a step, ignoring table]
15:10:28.715 [ERROR] Failed to respond to API request. Could not write response WSASend tcp 127.0.0.1:59942: An existing connection was forcibly closed by the remote host.
```

When Intellij IDEA is reopened, neither the specs nor the concepts have been changed.

I am not able to reproduce this in a fresh project, leading me to think that it only happens in a project with many specs.

As a possibly mitigating factor, we use Perforce for version control, which makes all files read-only until they are checked out. Normally, this is not an issue for refactoring (rename refactoring files results in an Intellij IDEA dialog asking to check them out), but I figured it ought to be mentioned.

This error was spotted with version 0.0.14 of the Intellij plugin and both Gauge 0.2.1 and a prerelease version of Gauge 0.2.2 given to test a fix for an unrelated issue.

**Comment by sriv** [comment]
Closing as stale. Please comment/reopen if this is still valid.
