### ISSUE TITLE
Extra letter appears when autocompleting a step without a space after the step asterisk

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/Intellij-Plugin#108]
To reproduce:

 1. On a new line in a spec, type an asterisk (`*`) at the beginning of a line as is typically done with new steps. But don't follow it with a space.
 2. Type the first few letters of a step name (e.g. `Say` for `Say <greeting> to <product name>`)
 3. Press enter

The result will be a line that says the following:

    *SSay <greeting> to <product name>

Instead of a space after the asterisk, the first letter of the step name was inserted. The expected beahvior would be for a space to be inserted instead as follows:

    * Say <greeting> to <product name>

**Comment by kashishm** [comment]
We have released [Gauge-Intellij 0.0.15](https://github.com/getgauge/Intellij-Plugin/releases/tag/v0.0.15) with the fix. Feel free to reopen the issue if you see the same behaviour in the new version.

**Comment by Thunderforge** [comment]
Should autocomplete add a space after the asterisk? Right now, we get:

    *Say <greeting> to <product name>

**Comment by kashishm** [comment]
For now it does not add a space char, but you can use `Spec Format (ctrl + alt + shift + l)` to do the formatting which will take care of the space char after the asterisk.

<img width="423" alt="screen shot 2015-12-03 at 10 41 17 am" src="https://cloud.githubusercontent.com/assets/5915802/11552422/6d38a3cc-99aa-11e5-9f0b-5d62741a617c.png">

**Comment by Thunderforge** [comment]
Proper Markdown requires a space after an asterisk. In fact, the Gauge HTML Preview tab in Intellij IDEA doesn't even render without a space correctly:

**Markdown:**

    *Without space after asterisk

    * With space after asterisk

**GitHub Render:**

*Without space after asterisk

* With space after asterisk

**Gauge HTML Preview Render:**
![image](https://cloud.githubusercontent.com/assets/6200170/11564827/d6bacb2c-99a0-11e5-8249-e61a8355c4a3.png)


I think that autocomplete should result in proper Markdown, which renders properly in the HTML Preview tab, rather than something that is incompatible.

**Comment by kashishm** [comment]
I have created an issue(https://github.com/getgauge/Intellij-Plugin/issues/114) for this.

**Comment by Thunderforge** [comment]
@kashishm Thanks!
