### ISSUE TITLE
no Maven projects to display

### ISSUE THREAD

**Issue by falkoschumann** [getgauge/Intellij-Plugin#111]
When I open a Maven project using Gauge the *Maven Project* view from IntelliJ shows the Lifecycle, Plugins and Dependencies. But when I update the POM and IntelliJ auto import this changes, the view is empty an display "There are no Maven projects to display." Well, I can not add the project again.

I must delete all IntelliJ stuff (`.idea`, `*.iml`) and open the pom.xml as project again. Then "Maven Project" shows the POM. But with the next change in POM the view is empty already.

**Comment by kashishm** [comment]
We have released [Gauge-Intellij 0.0.15](https://github.com/getgauge/Intellij-Plugin/releases/tag/v0.0.15) with the fix. Feel free to reopen the issue if you see the same behaviour in the new version.
