### ISSUE TITLE
no classpath module in run configuration

### ISSUE THREAD

**Issue by falkoschumann** [getgauge/Intellij-Plugin#112]
I have configure a Java project with Maven using Gauge. If I run a main method from source the application starts and a run configuration is created. But if I edit the run configuration there is no classpath module. The *Run/Debug Configurations* dialog shows only *<no module>* for *Use class path of module*. So I can not start the configuration again.

There may be a connection with #111.

**Comment by kashishm** [comment]
We have released [Gauge-Intellij 0.0.15](https://github.com/getgauge/Intellij-Plugin/releases/tag/v0.0.15) with the fix. Feel free to reopen the issue if you see the same behaviour in the new version.
