### ISSUE TITLE
Intellij crashes when using gauge tool

### ISSUE THREAD

**Issue by marti6adams** [getgauge/Intellij-Plugin#124]
So the problem is definitely in gauge, because once I stop the process from task manager Intellij is working fine. 
gauge version: 0.1.0
Intellij IDEA 15.0.4

No error logs are available, because IDEA just freezes and only task manager helps to end the process. The problem is the same on the other computers.

**Comment by mahendrakariya** [comment]
@marti6adams Apologies for the delayed response. But I am just wondering if you are still facing this issue?

**Comment by sguptatw** [comment]
Closing this issue, please re-open if the issue persists.
