### ISSUE TITLE
Method/Class X is never used

### ISSUE THREAD

**Issue by pavelpp** [getgauge/Intellij-Plugin#125]
Currently step classes and methods are always marked as never used in IntelliJ. I'd like to see a real picture when I open steps classes. Adding @SuppressWarnings("unused") looks like an overkill.

**Comment by kashishm** [comment]
Fix will be available in nightly > 3/5/2016

**Comment by sguptatw** [comment]
Getting the safe delete for a step which has an implementation

Related Issues

- [ ] https://github.com/getgauge/Intellij-Plugin/issues/145

**Comment by kashishm** [comment]
@sguptatw #145 is closed. Can we close this now
