### ISSUE TITLE
After initialization of Gauge-Maven project in IntelliJ, the IDE features don't work(needs project reload)

### ISSUE THREAD

**Issue by kashishm** [getgauge/Intellij-Plugin#129]

**Comment by Apoorva-GA** [comment]
Not replicable with latest(0.3.11) gauge intellij plugin.
and 
Gauge version: 0.9.9
Commit Hash: b4161b4

Plugins
-------
html-report (4.0.5.nightly-2018-05-03)
java (0.6.8)
spectacle (0.1.2)
