### ISSUE TITLE
Go to def doesn't work for the step if there is no character present after the step text.

### ISSUE THREAD

**Issue by kashishm** [getgauge/Intellij-Plugin#130]
Sample spec

```
Specification Heading
=====================

Vowel counts in single word
---------------------------

tags: single word

* The word "gauge" has "3" vowels.
```

go to def doesn't work when the cursor is at the end of step(The word "gauge" has "3" vowels.) i.e after `.` char. But after putting space or new line char it works.

**Comment by sriv** [comment]
Closing as stale. Please comment/reopen if this is still valid.
