### ISSUE TITLE
Table defined after a step and a comment is highlighted as table param instead of comment

### ISSUE THREAD

**Issue by kashishm** [getgauge/Intellij-Plugin#132]
In the following image, table should not be highlighted as it is a comment
<img width="359" alt="screen shot 2016-04-08 at 10 52 17 am" src="https://cloud.githubusercontent.com/assets/5915802/14374840/4ff5c164-fd78-11e5-9d8c-9aa7faf81f77.png">

Refactoring is also showing that step(`Almost all words have vowels`) has a table param
<img width="526" alt="screen shot 2016-04-08 at 10 52 29 am" src="https://cloud.githubusercontent.com/assets/5915802/14374841/502d6506-fd78-11e5-9658-00caf234f303.png">

**Comment by sriv** [comment]
Closing as stale. Please comment/reopen if this is still valid.
