### ISSUE TITLE
Should not allow implementation of an empty step

### ISSUE THREAD

**Issue by kashishm** [getgauge/Intellij-Plugin#134]
_From @sguptatw on April 18, 2016 7:19_

### Expected behavior
Should give parse error when empty step is created and implemented.
OR
Should not implement a step with no description

### Actual behavior
Allows the creation and implementation of empty step.

### Steps to reproduce
1. Create a scenario with "" step
2. Implement the step
3. Refactoring (shift F6) this gives an error.

### Gauge version
```
Run gauge -v on your system and paste the results here.
```

_Copied from original issue: getgauge/gauge#330_

**Comment by mahendrakariya** [comment]
@sguptatw The fix should be available in the nightly build > 2014-04-29

**Comment by sguptatw** [comment]
If the user enters space after the star and then gives the step implementation it still gets implemented
