### ISSUE TITLE
Getting a parse error for some special chars in table

### ISSUE THREAD

**Issue by kashishm** [getgauge/Intellij-Plugin#135]
_From @sguptatw on April 20, 2016 6:26_
### Expected behavior

Should not get a parse error in IntelliJ for a valid spec
### Actual behavior

Gives a parser error in IntelliJ for a valid spec
### Steps to reproduce
1. Create a spec with the following table

```
|example|
|--------|
|+|
|||
|\\|
```
1. Gives a parse error but execution works fine.
### Gauge version

```
0.4.0
```

_Copied from original issue: getgauge/gauge#346_

**Comment by sriv** [comment]
Closing as stale. Please comment/reopen if this is still valid.
