### ISSUE TITLE
Specs defined outside the specs folder are not getting executed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#141]
### Expected behavior
I should be able to define the specs in a different folder.

### Actual behavior
Specs defined outside the specs folder are not getting executed from IntelliJ

### Steps to reproduce
1. Create a folder specs1
2. Create a spec under specs1 folder
```
Specification Headings
=====================

Abc
-----
* ppp
```
3. Implementation
```
    @Step("ppp")
    public void implementation1() {
    }

```
4. Unable to execute the spec

```
Gauge version: 0.4.1.nightly-2016-04-19

Plugins
-------
html-report (2.1.0)
java (0.3.4.nightly-2016-04-19)
```

**Comment by kashishm** [comment]
Cannot reproduce this issue.

```
IntelliJ version: 2016.1.3
Gauge IntelliJ plugin version: 0.2.1
Gauge version: 0.5.1
Plugins
-------
java (0.4.1)
```
