### ISSUE TITLE
Table parameter not getting generated as a parameter value

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#143]
### Expected behavior
Table parameter should get generated as a parameter value

### Actual behavior
Table parameter not getting generated as a parameter value

### Steps to reproduce
1. Create a spec file 
```
Something
=========

sfsdfsdf
--------

* they all to come to the same thing
    |HEADER|
    |value|
    |value|
```

2. use create a step implementation.
3. The generated implementation does not have a parameter

### Gauge version
```
Gauge version: 0.4.1.nightly-2016-04-19

Plugins
-------
html-report (2.1.0)
java (0.3.4.nightly-2016-04-19)
```

**Comment by kashishm** [comment]
Cannot reproduce this issue.

```
IntelliJ version: 2016.1.3
Gauge IntelliJ plugin version: 0.2.1
Gauge version: 0.5.1
Plugins
-------
java (0.4.1)
```

**Comment by sguptatw** [comment]
Yes it is not replicable on the latest nightlies.
