### ISSUE TITLE
Invalid param mismatch error in step implementation

### ISSUE THREAD

**Issue by kashishm** [getgauge/Intellij-Plugin#146]
* create a new Gauge project in IntelliJ.
* Change the following implementation
```
@Step("Almost all words have vowels <table>")
    public void verifyVowelsCountInMultipleWords(Table wordsTable) {
}
```

to

```
@Step("Almost all words have vowels")
    public void verifyVowelsCountInMultipleWords() {
}
```

* IntelliJ gives error `Param count mismatch found [0] expected [1]`

**Comment by BugDiver** [comment]
Did a quick analysis. The root cause of this issue is `StepUtil.stepValueCache` is not getting invalidated when refactoring is done.

**Comment by BugDiver** [comment]
Duplicate of #144.
