### ISSUE TITLE
Project creation when gauge is uninstalled has src and corresponding folders generated with gauge-intelliJ plugin

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#150]
**Expected Behavior**
When gauge is uninstalled, the gauge-IntelliJ plugin project creation should not create the project.

**Actual Behavior**
It creates a project with idea and src/test/java folders.

**Steps to reproduce**
1. Uninstall gauge.
2. Create a `Gauge` project in IntelliJ
3. It gives an error but creates the project with src/test/java folder

**Comment by mahendrakariya** [comment]
Fix should be available in nightly >= 2016-06-09.

**Comment by sguptatw** [comment]
The project folder is going to get created because it is created by IntelliJ.
