### ISSUE TITLE
Gauge-IntelliJ installed and Gauge uninstalled has several issues

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#151]
**Expected Behavior**
Should not perform any actions related to gauge.

**Actual Behavior**
Performs the following inconsistently
```
1. Step implementation
2. Validates java file for parameter mismatch
3. Refactor the name
```

1. Create a new project using `Gauge`
2. Uninstall gauge
3. Re-open project
4. Create step implementation of concept
```
# 2 <werwer> two
* abc "def"
```

```
    @Step("* abc "def"")
    public void implementation1() {

    }
```

5. StepImplementation.java shows some invalid errors
```
Parameter count mismatch
```
Implement a step from a spec file. 
```
9:49:07 AM IncorrectOperationException: Incorrect method '@Step("* 1
")
public void implementation1(){

}
```

**Comment by mahendrakariya** [comment]
Some of the functionalities of Gauge IntelliJ plugin will continue to work if there is no dependency on Gauge. For example, syntax highlight, step implementation, etc.

This is by design.

**Comment by mahendrakariya** [comment]
When Gauge is not installed and a Gauge project is opened in IntelliJ, the latest nightly version should show an error about Gauge not being installed.

**Comment by sguptatw** [comment]
It is showing the error in the bubble.
