### ISSUE TITLE
Adding a gauge module to an existing maven web app project is not synchronizing the src file

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#152]
### Expected behavior
Adding a gauge module to an existing maven web app project should synchronizing the src file

### Actual behavior
Adding a gauge module to an existing maven web app project is not synchronizing the src file

### Steps to reproduce
1. I have created the attached project using the maven  
```
mvn archetype:generate -DgroupId=tw.gauge -DartifactId=CounterWebApp -DarchetypeArtifactId=maven-archetype-webapp -DinteractiveMode=false
```
2. open the project in IntelliJ
[CounterWebApp.zip](https://github.com/getgauge/Intellij-Plugin/files/258595/CounterWebApp.zip)

3. Add a `Gauge` module. By default the src files are not getting synched and hence the issue

### Versions
```
Gauge version: 0.4.1.nightly-2016-05-09

Plugins
-------
html-report (2.1.1.nightly-2016-05-10)
java (0.4.0.nightly-2016-05-09)
ruby (0.2.0.nightly-2016-05-09)
xml-report (0.1.2.nightly-2016-05-09)
```

**Comment by mahendrakariya** [comment]
Unable to reproduce with the given steps. All the folders in the new Gauge module are synchronizing as expected.

**Comment by kashishm** [comment]
Fix will be available in nightly >= 2016-06-17
