### ISSUE TITLE
Step is getting highlighted as scenario heading

### ISSUE THREAD

**Issue by kashishm** [getgauge/Intellij-Plugin#153]
For the following spec, `* abc` is getting highlighted as scenario heading but Gauge is executing `* abc` as a step. However when one tries to goto the definition of it. It says 'Cannot find declaration to goto'.

```
sf
==
Scenario Heading
----------------
* abc
-------
* def
```

**Comment by sriv** [comment]
Closing as stale. Please comment/reopen if this is still valid.
