### ISSUE TITLE
Unimplemented steps are shown as implemented

### ISSUE THREAD

**Issue by apoorvam** [getgauge/Intellij-Plugin#155]
_From @sguptatw on April 21, 2016 10:32_
### Expected behavior

Unimplemented steps should show as unimplemented
### Actual behavior

Spec with only context steps show the steps as implemented
### Steps to reproduce

1.

```
Something
=========

* something else
* This is showing as implemented

```
1. The steps are shown as unimplemented
### Gauge version

```
Gauge version: 0.4.1.nightly-2016-04-19

Plugins
-------
html-report (2.1.0)
java (0.3.4.nightly-2016-04-19)
```

_Copied from original issue: getgauge/gauge#352_

**Comment by BugDiver** [comment]
Syntax highlighting is handled by IntelliJ and it heavily depends on the parsing that is done based on the defined grammar. This issue should be handled along with other [grammar](https://github.com/getgauge/Intellij-Plugin/labels/grammar) issues.

**Comment by kashishm** [comment]
To fix this issue we might have to change the grammar of spec file.

For now, spec file requires one or more scenario to be present. Refer [this line](https://github.com/getgauge/Intellij-Plugin/blob/master/src/specification.bnf#L36). We may have to change this line to 
```
specFile ::= specDetail scenario*
```

**Comment by kashishm** [comment]
Fix will be available in nightly >= 2016-12-22
