### ISSUE TITLE
Unable to run test from the IDE

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#157]
**Expected Behavior**
If the specs are executable from command line, one should be able to execute it from the IDE.

**Actual Behavior**
Able to run the spec from command line.
```
Error: Could not find or load main class com.thoughtworks.gauge.GaugeRuntime
process /Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/bin/java with pid 5297 quit unexpectedly. exit status 1
```

**Steps to replicate**
1. Create a spec
2. From command line uninstall gauge-java
3. Go back to the IDE. It shows various errors.
4. From the command line install gauge java from file.
5. execute the project from IDE.
6. It fails. Reload the project.
7. Run the specs. It gives the above error.

**Version**
```
Gauge version: 0.4.1.nightly-2016-06-06

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-05-30)
```

**Comment by mahendrakariya** [comment]
@sguptatw What is the project classpath?

**Comment by kashishm** [comment]
Fix will be available in nightly >= 10/06/2016

**Comment by sudhirsadhanala** [comment]
I have the same issue can anyone please let me know what needs to be done
I have gauge version 0.8.1
Plugin: html-report (3.1.0)
java(0.6.1)

**Comment by sudhirsadhanala** [comment]
"C:\Program Files\Gauge\bin\gauge.exe" --simple-console C:/Users/sudhsa/Downloads/GauageSampleProject/specs/hello_world.spec
Error: Could not find or load main class com.thoughtworks.gauge.GaugeRuntime
process C:\ProgramData\Oracle\Java\javapath\java.exe with pid 10124 quit unexpectedly. exit status 1
Failed to start gauge API: Runner with pid 8708 quit unexpectedly(exit status 1).

Process finished with exit code 1

**Comment by sudhirsadhanala** [comment]
Runner connection error: Runner with pid 5864 quit unexpectedly(exit status 1):  from logs

**Comment by VikasSalunke** [comment]
I am getting the same error. Did u got the Solution?

**Comment by sudhirsadhanala** [comment]
No vikas, we moved on with cucumber jvm.
