### ISSUE TITLE
Getting "Failed to start ... The filename or extension is too long." when running in Idea

### ISSUE THREAD

**Issue by henkeja** [getgauge/Intellij-Plugin#164]
When trying to run my spec in Idea (shift+F10), I'm getting the following (in the Run Tool Window):

"C:\Program Files\Gauge\bin\gauge.exe" --simple-console C:/dev/apps/compilerservice/tests-gauge/specs/compilerService.spec
Failed to start C:\Program Files (x86)\Java\jdk1.7.0_79\jre\bin\java.exe. fork/exec C:\Program Files (x86)\Java\jdk1.7.0_79\jre\bin\java.exe: The filename or extension is too long.
Failed to start gauge API: Timed out connecting to [::]:54480

Process finished with exit code 1

This just started today, I have been running fine for the last few weeks. 
Running in the Terminal Tool Window or in a dos box it works fine.

### Versions

* Gauge IntelliJ plugin Version: 0.1.0
* Gauge version: 0.4.0

Plugins:
html-report (2.1.0)
java (0.4.0)

**Comment by mahendrakariya** [comment]
Could you please try clearing the IntelliJ cache and restart it? You can do so from the `File` menu.

**Comment by henkeja** [comment]
Thanks for getting back to me, I tried clearing the cache and I'm still getting the same error. I also upgraded to the new version 0.2.0 Gauge plugin and that did not make a difference.

**Comment by mahendrakariya** [comment]
@henkeja Thanks for the info. We will take a look at it.

I would also like to point out that v0.2.0 of Gauge IntelliJ plugin is not compatible with Gauge v0.4.0. If you updated the IntelliJ plugin, please update Gauge as well. Latest Gauge version is 0.5.0. You can download it from [Gauge website](http://getgauge.io/get-started/index.html). After updating, please ensure to run `gauge --update-all` so that so are on the latest version of all the plugins.

**Comment by henkeja** [comment]
Thanks for the heads up, I have installed Gauge 0.5.0. - problem still there.

**Comment by kashishm** [comment]
Could you please tell us if the project is using any build tool(Gradle/Maven)?

**Comment by henkeja** [comment]
We are using Gradle, but the project is not setup as a Gradle project.

**Comment by kashishm** [comment]
We could not reproduce this issue.
Can you replicate the issue on a sample Gauge project? If yes, please send us that sample project.

**Comment by henkeja** [comment]
In doing some review of the code, I noticed that something had changed the Java version from 1.7.0_76 to 1.8.0_91. When I changed it back to Java 7 the error went away, I'm running fine now.

**Comment by dengayevskiy** [comment]
Hi guys! 

I have the same problem with my build. I'm on windows 10, build tool is maven 3.5.0. 

Issue is reproduced on the project with huge classpath like mine. I think it is connected to https://github.com/bazelbuild/bazel/issues/2242.
