### ISSUE TITLE
Parameters of the method is marked for safe deletion.

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#169]
### Expected behavior

Parameters of the gauge implementation method should not be marked for deletion. Since it is used in the step text.
### Actual behavior

Parameters of the method no implementation details is marked as safe for deletion. However it is used in the step annotation.
### Steps to reproduce
1. Create a spec with a step
2. Implement the step
3. See the implementation code.
- IntelliJ version and edition(Community/Ultimate)
  IntelliJ 2016.1.2
- OS information
  Windows
- Gauge IntelliJ plugin version.
  17/06/2016 nightly
- Does the project uses any Build tool(Gradle/Maven)?
  No
- Run gauge -v on your system and paste the results here.

```
Gauge version: 0.5.1.nightly-2016-06-16

Plugins
-------
csharp (0.8.0.nightly-2016-06-17)
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-06-16)
ruby (0.2.0)
xml-report (0.1.2.nightly-2016-05-03)
```

**Comment by kashishm** [comment]
Fix will be available in nightly >= 2016-12-22
