### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by apps4u** [getgauge/Intellij-Plugin#174]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Information that will help us debug

* IntelliJ version and edition(Community/Ultimate)
* OS information
* Gauge IntelliJ plugin version.
* Does the project uses any Build tool(Gradle/Maven)?
* Run gauge -v on your system and paste the results here.

**Comment by sriv** [comment]
Looks like the issue content got missed out, all I see is the template. Could you please provide some details about the issue you are facing?
