### ISSUE TITLE
Starting IntelliJ Gauge error

### ISSUE THREAD

**Issue by neon096** [getgauge/Intellij-Plugin#178]
### Expected behavior
No errors reported by IntelliJ

### Actual behavior
IntelliJ started up and said there was an error by gauge.

08:00	Exception occurred in Gauge plugin: Please log an issue here with the following details and reload the project.
			```
			```
			* Idea version: 2016.2.1
			* API version: IC-162.1447.26
			* Plugin version: 0.2.1
			* Gauge version: 0.6.0 (show balloon)

### Steps to reproduce
1. Start IntelliJ
2.
3.

### Information that will help us debug

* IntelliJ version and edition(Community)
* OS information Windows 7
* Gauge IntelliJ plugin version.  0.2.1
* Does the project uses any Build tool(Maven)?
* Run gauge -v on your system and paste the results here.
Gauge version: 0.6.0

Plugins
-------
html-report (2.1.1)
java (0.5.0)
xml-report (0.1.1)

**Comment by BugDiver** [comment]
@neon096 could you please try to install [nightly](gauge-java-intellij-0.2.2.nightly-2016-08-10.zip) version of the plugin and see if the issue still exists.

**Comment by madhura-optymyze** [comment]
doesn't work inspite of using this nightly version 0.2.2.nightly-2016-08-12

**Comment by kashishm** [comment]
I have pushed a commit which addresses the issue and the [0.2.2.nightly-2016-08-29](https://bintray.com/gauge/Gauge-Java-Intellij/Nightly) nightly version of the plugin has the fix.

**Comment by kashishm** [comment]
Fix is available in the latest release. Feel free to reopen the issue if you still face the same problem.
