### ISSUE TITLE
Errors when Opening IntelliJ Project

### ISSUE THREAD

**Issue by brown131** [getgauge/Intellij-Plugin#179]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1. Opened our project.
2. The error event windows appeared.
3.

### Information that will help us debug

				* Idea version: 2016.2.1
				* API version: IU-162.1447.26
				* Plugin version: 0.2.1
				* Gauge version: null (show balloon)

* IntelliJ version and edition(Community/Ultimate)
* OS information
* Gauge IntelliJ plugin version.
* Does the project uses any Build tool(Gradle/Maven)?
* Run gauge -v on your system and paste the results here.

**Comment by kashishm** [comment]
@brown131 Could you please try to install the [latest](https://bintray.com/gauge/Gauge-Java-Intellij/Nightly) nightly version of the plugin and see if the issue still exists?

**Comment by brown131** [comment]
The errors no longer appear when I open the project. Thanks! :)
