### ISSUE TITLE
Gauge API not started error on IDEA start-up

### ISSUE THREAD

**Issue by praveen-cimplicity** [getgauge/Intellij-Plugin#181]
26/08/16
2:15 PM	Exception occurred in Gauge plugin: Please log an issue here with the following details and reload the project.
				```
Gauge version: 0.6.1

Plugins
-------
html-report (2.1.1)
java (0.5.0)
ruby (0.3.0)
xml-report (0.1.3)
			
				
				
				
				
				
				
				
				
				
				
				
				
				
				
				
				
				
				
				
				
				
				```
				* Idea version: 2016.2.2
				* API version: IU-162.1628.40
				* Plugin version: 0.2.1
				* Gauge version: 0.6.1

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Information that will help us debug

* IntelliJ version and edition(Community/Ultimate)
* OS information
* Gauge IntelliJ plugin version.
* Does the project uses any Build tool(Gradle/Maven)?
* Run gauge -v on your system and paste the results here.

**Comment by kashishm** [comment]
I have pushed a commit which addresses the issue. Could you please try to install the [latest](https://bintray.com/gauge/Gauge-Java-Intellij/Nightly) nightly version of the plugin and see if the issue still exists?

**Comment by kashishm** [comment]
Fix is available in the latest release. Feel free to reopen the issue if you still face the same problem.
