### ISSUE TITLE
Right clicking on some steps of a given scenario and running the spec should run the given spec

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#182]
### Expected behavior

Right clicking on some steps of a given scenario and running the spec should run the given spec.
### Actual behavior

Right clicking on some steps of a given scenario and running the spec is running the entire spec
### Steps to reproduce
1. Create a spec

```
Specification Heading
=====================


    |VowelCount|
    |1|
    |2|
    |3|


* Vowels being "aeiou"

Vowel counts in single word
---------------------------

tags: single word

* The word "gauge" has <VowelCount> vowels.

Vowel counts in multiple word
-----------------------------

This is the second scenario in this specification

Here's a step that takes a table

* Almost all words have vowels 

     |Word  |Vowel Count|
     |------|-----------|
     |Gauge |3          |
     |Mingle|2          |
     |Snap  |1          |
     |GoCD  |1          |
     |Rhythm|0          |
```
1. Right click on a step `The word "gauge" has <VowelCount> vowels.`
2. Run the spec.
   It is running all the scenarios.
### Information that will help us debug

```
IntelliJ IDEA 2016.1.2
Build #IC-145.972, built on May 14, 2016
JRE: 1.8.0_76-release-b162 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```
- OS information
  OSX Yosemite Version 10.10.5
- Gauge IntelliJ plugin version.
  gauge-java-intellij-0.2.2.nightly-2016-08-12.zip
- Does the project uses any Build tool(Gradle/Maven)?
  No
- Run gauge -v on your system and paste the results here.

```
Gauge version: 0.6.2.nightly-2016-08-05

Plugins
-------
csharp (0.9.1.nightly-2016-08-12)
html-report (2.2.0.nightly-2016-08-15)
java (0.5.1.nightly-2016-08-18)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by kashishm** [comment]
Fix will be available in nightly >= 0.2.6.nightly-2017-01-03. Follow the instructions in [documentation](http://getgauge.io/documentation/user/current/ide_support/intellij_idea.html#installing-nightly) to install the plugin from the nightly channel.
