### ISSUE TITLE
Syntax highlight: Does not highlight syntax highest spec folder is not the default folder.

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#189]
**Expected behavior**
The syntax should be highlighted irrespective of the containing folder.

**Actual behavior**
Does not highlight syntax highest spec folder is not the default folder.

**Comment by apoorvam** [comment]
Syntax highlighting is working fine in the case of spec files present in folders other than default `specs` folder as well. 
Works as of nightly >= 3.1.2017
