### ISSUE TITLE
Extract to concept:Should not be able to extract to a spec or other file types.

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#192]
**Expected behavior**
Should be able to extract only to a file with cpt extension

**Actual behavior**
Able to extract to any file type.

**Version**
```
Gauge version: 0.6.2.nightly-2016-09-02

Plugins
-------
csharp (0.9.1.nightly-2016-08-12)
html-report (2.2.0.nightly-2016-08-28)
java (0.5.1.nightly-2016-08-18)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```
**IntelliJ**
`gauge-java-intellij-0.2.4.nightly-2016-09-05`

**Comment by kashishm** [comment]
The fix is available in IntelliJ nightly >= 0.2.4.nightly-2016-09-14 and Gauge nightly >= 0.6.2.nightly-2016-09-13

**Comment by sguptatw** [comment]
@kashishm :
Before the existing concepts were getting listed in the autocomplete text box. Now only the paths are available. Is this intentional

**Comment by kashishm** [comment]
In the new file name field, only paths are listed but in the dropdown you will see concepts file. We have not changed any behaviour in this fix.

**Comment by sguptatw** [comment]
Selecting the file from the dropdown and continuing is giving the error that the file name should end with .cpt
