### ISSUE TITLE
Extract to concept:Should check if this extraction will give raise to duplicate concept definitions

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#193]
**Expected behavior**
Should check if this extraction will give raise to duplicate concept definitions. If yes, then it should give an error.

**Actual behavior**
Continues with extraction

**Version**
```
Gauge version: 0.6.2.nightly-2016-09-02

Plugins
-------
csharp (0.9.1.nightly-2016-08-12)
html-report (2.2.0.nightly-2016-08-28)
java (0.5.1.nightly-2016-08-18)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```
IntelliJ
`gauge-java-intellij-0.2.4.nightly-2016-09-05`

**Comment by kashishm** [comment]
The fix is available in IntelliJ nightly >= 0.2.4.nightly-2016-09-14 and Gauge nightly >= 0.6.2.nightly-2016-09-13
