### ISSUE TITLE
Should expand/collapse a scenario with comments after the last step

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#196]
**Expected behavior**
The comments after the last step in a scenario should be part of the expand/collapse of the scenario.

**Actual behavior**
The comments after the last step is not part of the collapsed scenario

**Steps to replicate**
1. Create a spec

```
Something
=========

Scenario Heading
----------------
tags: sdfsdf

* Step that takes a table1
* Concept Heading37a
* abcdefg "a" 

     |sfsdf|
     |-----|
     |a    |
sdfsdf

sdfsdfsdf

sdfsdfsdf

Abc

---
* sfsdfsdf
__________

* fhfgh

```
1. expand/collapse `Scenario Heading`.

**Version**
IntelliJ

```
gauge-java-intellij-0.2.4.nightly-2016-09-12
```

```
Gauge version: 0.6.2.nightly-2016-09-13

Plugins
-------
csharp (0.9.1.nightly-2016-08-12)
html-report (2.2.0.nightly-2016-08-28)
java (0.5.1.nightly-2016-09-09)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by kashishm** [comment]
Fix will be available in nightly >= 2016-10-26

**Comment by sguptatw** [comment]
This is still having issues with scenario steps above and below the tear down separator.

**Comment by sguptatw** [comment]
Working fine now
