### ISSUE TITLE
Behavior of expand/collapse tear down steps inconsistent

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#197]
**Expected behavior**
The teardown steps should either not have the expand/collapse option or it should have an independent expand/collapse

**Actual behavior**
It is currently having the expand/collapse option and is collapsing into the last scenario
One more thing to consider, context steps do not have expand/collapse. Should the teardown steps have expand/collapse

**Steps to replicate**
1. Create a spec
```
Something
=========
Scenario Heading
----------------
tags: sdfsdf

* Step that takes a table1
* Concept Heading37a
* abcdefg "a" 

     |sfsdf|
     |-----|
     |a    |
_____________________

* sfsdfsdf
__________

* fhfgh
```
2. Try expanding and collapsing the scenario

**Version**
IntelliJ
```
gauge-java-intellij-0.2.4.nightly-2016-09-12
```
```
Gauge version: 0.6.2.nightly-2016-09-13

Plugins
-------
csharp (0.9.1.nightly-2016-08-12)
html-report (2.2.0.nightly-2016-08-28)
java (0.5.1.nightly-2016-09-09)
ruby (0.3.2.nightly-2016-08-22)
spectacle (0.0.1)
xml-report (0.1.4.nightly-2016-07-25)
```

**Comment by kashishm** [comment]
Fix will be available in nightly >= 2016-10-26
