### ISSUE TITLE
does not start

### ISSUE THREAD

**Issue by gizdolok** [getgauge/Intellij-Plugin#200]
### Expected behavior

Tell us what should happen
### Actual behavior

Tell us what happens instead
### Steps to reproduce

1.
2.
3.
### Information that will help us debug
- IntelliJ version and edition(Community/Ultimate)
- OS information
- Gauge IntelliJ plugin version.
- Does the project uses any Build tool(Gradle/Maven)?
- Run gauge -v on your system and paste the results here.

```
```
- Idea version: 15.0.6
- API version: IC-143.2370
- Plugin version: 0.2.1
- Gauge version: 0.6.2

**Comment by mahendrakariya** [comment]
@gizdolok Could you please let us know what is the error message that you see on the screen?
