### ISSUE TITLE
With table column name missing, the spec file does not give the goto step definition

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/Intellij-Plugin#201]
_From @sguptatw on June 17, 2016 11:28_

**Expected behavior**
Features like goto definition or create step implementations are working when there are other parse errors. It should work when a table does not have a header.

**Actual behavior**
Does not give me options to create/navigate a step

**Steps to replicate 
1. Create a spec

```
Something
=========
||
|---|
||
Scenario Heading
----------------
* Step that takes a table1 <dynamic>
* s"a˘bc"
* s"def"
```
1. Unable to perform the above mentioned operations

**Version**

```
Gauge version: 0.5.1.nightly-2016-06-16

Plugins
-------
html-report (2.1.1.nightly-2016-06-02)
java (0.4.1.nightly-2016-06-16)
xml-report (0.1.2.nightly-2016-05-27)
```

_Copied from original issue: getgauge/gauge#458_

**Comment by apoorvam** [comment]
Fix should be available in nightly >= 3.1.2017
