### ISSUE TITLE
Refactor step changes special UTF-8 character to invalid character (ü to Ã¼)

### ISSUE THREAD

**Issue by kashishm** [getgauge/Intellij-Plugin#202]
_From @kupna on July 20, 2016 7:50_

When I refactor a step in a spec file where special UTF-8 characters like ü are used, after refactoring they are changed to invalid characters like Ã¼

![image](https://cloud.githubusercontent.com/assets/12813719/16979049/59c5d534-4e5f-11e6-8195-b210a04d0432.png)

_Copied from original issue: getgauge/gauge-java#64_

**Comment by kashishm** [comment]
_From @kupna on October 11, 2016 9:1_

when will you fix this?

**Comment by kashishm** [comment]
@sguptatw The fix will be available in nightly >= 2016-10-12

@kupna This issue is fixed in the latest nightly. If you like to try out, you can download it from [here](https://bintray.com/gauge/Gauge-Java-Intellij/Nightly/) and install.

**Comment by sguptatw** [comment]
Test case
```
* abcdefg "à, è, ì, ò, ù - À, È, Ì, Ò, Ù	CTRL+` (ACCENT GRAVE), the letter"
* abcdefg "á, é, í, ó, ú, ý - Á, É, Í, Ó, Ú, Ý	CTRL+' (APOSTROPHE), the letter"
* abcdefg "â, ê, î, ô, û Â, Ê, Î, Ô, Û 	CTRL+^ (CARET), the letter"
* abcdefg "ã, ñ, õ Ã, Ñ, Õ 	CTRL+~ (TILDE), the letter"
* abcdefg "ä, ë, ï, ö, ü, ÿ Ä, Ë, Ï, Ö, Ü, Ÿ 	CTRL+: (COLON), the letter"
* abcdefg "å, Å 	CTRL+@, a or A"
* abcdefg "æ, Æ 	CTRL+&, a or A"
* abcdefg "œ, Œ 	CTRL+&, o or O"
* abcdefg "ç, Ç 	CTRL+, (COMMA), c or C"
* abcdefg "ð, Ð 	CTRL+' (APOSTROPHE), d or D"
* abcdefg "ø, Ø 	CTRL+/, o or O"
* abcdefg "¿	ALT+CTRL+?"
* abcdefg "¡ 	ALT+CTRL+!"
* abcdefg "ß 	CTRL+&, s"
```
is inserting some unwanted characters to 
```
* abcdefg"à, è, ì, ò, ù - À, È, Ì, Ò, Ù\tCTRL+` (ACCENT GRAVE), the letter"
* abcdefg"á, é, í, ó, ú, ý - Á, É, Í, Ó, Ú, Ý\tCTRL+' (APOSTROPHE), the letter"
* abcdefg"â, ê, î, ô, û Â, Ê, Î, Ô, Û \tCTRL+^ (CARET), the letter"
* abcdefg"ã, ñ, õ Ã, Ñ, Õ \tCTRL+~ (TILDE), the letter"
* abcdefg"ä, ë, ï, ö, ü, ÿ Ä, Ë, Ï, Ö, Ü, Ÿ \tCTRL+: (COLON), the letter"
* abcdefg"å, Å \tCTRL+@, a or A"
* abcdefg"æ, Æ \tCTRL+&, a or A"
* abcdefg"œ, Œ \tCTRL+&, o or O"
* abcdefg"ç, Ç \tCTRL+, (COMMA), c or C"
* abcdefg"ð, Ð \tCTRL+' (APOSTROPHE), d or D"
* abcdefg"ø, Ø \tCTRL+/, o or O"
* abcdefg"¿\tALT+CTRL+?"
* abcdefg"¡ \tALT+CTRL+!"
* abcdefg"ß \tCTRL+&, s"
```

**Comment by kupna** [comment]
When will this bug fix be available?

**Comment by kupna** [comment]
Is the bug fix still only available in the nightly build?

**Comment by sguptatw** [comment]
@kupna : No there are some more edge cases that needs to be addressed. We are working on it.

**Comment by kupna** [comment]
Ok then I will wait for the fix.

But how do I install the nightly build? I have done it before, but forgotten...

**Comment by sguptatw** [comment]
Steps to install Gauge Intellij IDEA plugin nightly from IDE:

* Download the [IntelliJ nightly](https://bintray.com/gauge/Gauge-Java-Intellij/Nightly)
* Open the Settings dialog (e.g. ⌘ Comma).
* In the left-hand pane, select Plugins.
* On the Plugins page that opens in the right-hand part of the dialog, click the Install JetBrains plugin or the Browse repositories button.
* In the dialog that opens, search for Gauge. Uninstall if already installed.
* Restart the IntelliJ and come back to the same plugins page.
* Use the `Install plugin from disk...` option.
* Select the downloaded plugin and complete the installation.

**Comment by sguptatw** [comment]
Steps to install Gauge Intellij IDEA plugin nightly from IDE:

* Download the [IntelliJ nightly](https://bintray.com/gauge/Gauge-Java-Intellij/Nightly)
* Open the Settings dialog (e.g. ⌘ Comma).
* In the left-hand pane, select Plugins.
* On the Plugins page that opens in the right-hand part of the dialog, click the Install JetBrains plugin or the Browse repositories button.
* In the dialog that opens, search for Gauge. Uninstall if already installed.
* Restart the IntelliJ and come back to the same plugins page.
* Use the `Install plugin from disk...` option.
* Select the downloaded plugin and complete the installation.

**Comment by zabil** [comment]
Closing this as stale. Please feel free to open if it's still an issue
