### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by gizdolok** [getgauge/Intellij-Plugin#213]
### Expected behavior
IntelliJ should load Gauge modules successfully

### Actual behavior
this crash occurs

### Steps to reproduce
1. Open IntelliJ

### Version information

* IntelliJ version and edition(Community/Ultimate): 
* OS information:
* Gauge IntelliJ plugin version:
* Does the project uses any Build tool(Gradle/Maven)?
```
Run gauge -v on your system and paste the results here
```

**Comment by kashishm** [comment]
@gizdolok Could you please share the error message and stacktrace?
