### ISSUE TITLE
Inconsistency in behavior - single step scenarios should have similar option to expand collapse

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#219]
### Expected behavior
The expand/collapse of a scenario with one step should be similar to scenario with multiple steps.

### Actual behavior
The expand/collapse of a scenario with one step does not have the option

### Steps to reproduce
1. Create a spec
```
Specification Heading2
======================
Scenario Heading
----------------
* how does SF work
Scenario Heading2
-----------------
tags: sdfsdf

* Step that takes a table1
```
2. `Scenario Heading` should have an expand/collapse option like `Scenario Heading2`

### Version information

* IntelliJ version and edition(Community/Ultimate): 
IntelliJ IDEA 2016.1.2
Build #IC-145.972, built on May 14, 2016
JRE: 1.8.0_76-release-b162 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

* OS information: Windows 10
* Gauge IntelliJ plugin version:
```
Gauge version: 0.7.1.nightly-2016-12-19

Plugins
-------
No plugins found
```
* Does the project uses any Build tool(Gradle/Maven)? No

**Comment by kashishm** [comment]
For single line/step scenarios also has this feature via cmd + shift + A -> collapse/expand or cmd -/+ but the visual indicator is missing.

**Comment by kashishm** [comment]
It's not currently possible to show expand/collapse folding anchors for scenarios having one line/step in IntelliJ. For more details, refer [this post](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000004164-FoldingBuilder-behavior-for-single-line?page=1).
