### ISSUE TITLE
The newlines between two scenarios should be retained when collapsed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#220]
### Expected behavior
The newlines is getting collapsed along with the other steps

### Actual behavior
The newlines at the end of the scenario should not get collapsed along with the scenario steps. - example code expand collapse in IntelliJ. The new lines between two methods does not get collapsed with the previous method.

### Steps to reproduce
1. Create a spec
```
Specification Heading2
======================
Scenario Heading
----------------
* how does SF work


Scenario Heading2
-----------------
tags: sdfsdf

* Step that takes a table1
```
2. collapse `Scenario Heading`. It should not collapse the newlines  between the scenarios.

### Version information

* IntelliJ version and edition(Community/Ultimate): 
IntelliJ IDEA 2016.1.2
Build #IC-145.972, built on May 14, 2016
JRE: 1.8.0_76-release-b162 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

* OS information: Windows 10
* Gauge IntelliJ plugin version:
```
Gauge version: 0.7.1.nightly-2016-12-19

Plugins
-------
No plugins found
```
* Does the project uses any Build tool(Gradle/Maven)? No

**Comment by kashishm** [comment]
Fix will be available in nightly >= 2016-12-21
