### ISSUE TITLE
Version information

### ISSUE THREAD

**Issue by xiangjing** [getgauge/Intellij-Plugin#221]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Version information

* IntelliJ version and edition(Community/Ultimate): 
* OS information:
* Gauge IntelliJ plugin version:
* Does the project uses any Build tool(Gradle/Maven)?
```
Run gauge -v on your system and paste the results here
```

**Comment by kashishm** [comment]
@xiangjing Could you please share the error message and stacktrace?
