### ISSUE TITLE
Gauge plugin doesn't start - can't find and load main class.

### ISSUE THREAD

**Issue by john-cooley** [getgauge/Intellij-Plugin#232]
### Expected behavior
Gauge plugin should start and run without issue.

### Actual behavior
Error: Could not find or load main class com.thoughtworks.gauge.GaugeRuntime

### Steps to reproduce
1. Start IDE with Gauge project
2.
3.

### Version information

* IntelliJ version and edition(Community/Ultimate): Community 2016.3.4
* OS information: Windows 10 on Intel Core i7
* Gauge IntelliJ plugin version: 0.8.0
* Does the project uses any Build tool(Gradle/Maven)? maven
```
Run gauge -v on your system and paste the results here
C:\Users\RAC3019\workspace\guage>gauge -v
Gauge version: 0.8.0

Plugins
-------
html-report (3.1.0)
java (0.6.1)

C:\Users\RAC3019\workspace\guage>

**Comment by kashishm** [comment]
@john-cooley Do you have [gauge-java](https://mvnrepository.com/artifact/com.thoughtworks.gauge/gauge-java) maven dependency in pom.xml? If not, please add it and then try starting/running specs.

**Comment by kashishm** [comment]
@john-cooley Please update Gauge to the latest version [0.8.4](https://github.com/getgauge/gauge/releases/tag/v0.8.4) and then try.

Reopen this if you see the exception again.
