### ISSUE TITLE
Could not start gauge api: Could not find executable in PATH or GAUGE_ROOT. error is coming in intellij

### ISSUE THREAD

**Issue by PrithviThakor** [getgauge/Intellij-Plugin#233]
### Expected behavior
Gauge plugin should work fine.

### Actual behavior
I had a community version of Intellij and gauge working fine. I uninstall the community version and installed the license version Intellij, after that intellij start showing "Could not start gauge api: Could not find executable in PATH or GAUGE_ROOT. Gauge is not installed.: Could not find executable in PATH or GAUGE_ROOT. Gauge is not installed." error message.

I have gauge installed in the default location. ( /usr/local/bin/gauge)

### Version information

* IntelliJ version and edition(Community/Ultimate): Ultimate 2016.3.5 ( Build #IU-163.13906.18, built on March 6, 2017 )
* OS information: MacOS Sierra ( Version 10.12.3 )
* Gauge IntelliJ plugin version: 0.3.1
* Does the project uses any Build tool(Gradle/Maven)? Yes - Maven
```
Run gauge -v on your system and paste the results here
Gauge version: 0.8.1

Plugins
-------
html-report (3.1.0)
java (0.6.1)

**Comment by PrithviThakor** [comment]
Resolved the issue. It was happening due my internal mac configuration.

**Comment by sriv** [comment]
@PrithviThakor - thanks for reverting back. If you  can share any information on how you troubleshooted this, it may help others.

**Comment by PrithviThakor** [comment]
Basically i had a custom script integrated as part of my ~/.bashrc which ask for password phrase every time any plugin or script to be executed. My understanding is gauge plugin was not able to get started because of the password asked ( it was happening on backend ), so i disabled it and it resolved my issue. Thanks !
