### ISSUE TITLE
Switching gauge projects caused a plugin crash

### ISSUE THREAD

**Issue by JDAQualityEnterprises** [getgauge/Intellij-Plugin#234]
### Expected behavior
Gauge project to load in IntelliJ 

### Actual behavior
The Gauge project loaded successfully (and tests could be run), but an error was displayed in the event log window

### Steps to reproduce
1. Load Gauge project (not using Gradle)
2. Close Gauge project
3. Select another Gauge project (Using Gradle)
4. Error displayed

![screenshot](https://cloud.githubusercontent.com/assets/18424271/23747362/47d94c34-04b7-11e7-9b3c-6f7e25c35deb.png)

### Version information

* IntelliJ version and edition(Community/Ultimate):  Community
IntelliJ IDEA 2016.3.5
Build #IC-163.13906.18, built on March 6, 2017
JRE: 1.8.0_112-release-408-b6 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

* OS information: Windows 10
* Gauge IntelliJ plugin version: 0.3.1
* Does the project uses any Build tool(Gradle/Maven)?
Gradle Version: 163.13906.18
Run gauge -v on your system and paste the results here
Gauge version: 0.8.1

Plugins
-------
html-report (3.1.0)
java (0.6.1)

**Comment by kashishm** [comment]
@JDAQualityEnterprises  Please make sure you have latest [gauge-java](https://mvnrepository.com/artifact/com.thoughtworks.gauge/gauge-java) dependency in `build.gradle`. Clear all the exceptions in IntelliJ and then try reloading the project.

**Comment by kashishm** [comment]
Please reopen the issue if you face this issue again.

**Comment by JDAQualityEnterprises** [comment]
Thanks Kashish
