### ISSUE TITLE
Upgrade failed, after downgrade no longer able to run Gauge 

### ISSUE THREAD

**Issue by khagberg** [getgauge/Intellij-Plugin#239]
### Expected behavior
Tell us what should happen
Gauge API should start

### Actual behavior
Tell us what happens instead
Gauge API does not start

### Steps to reproduce
1. Update to latest intellij 17.1
2. update gauge and gauge plugin
3. realize that it does not work due to bug that doesn't work with Twist migrations
4. Downgrade to 0.70 and plugin 0.2.1 -> produces failure when opening project in intellij

### Version information

* IntelliJ version and edition(Community/Ultimate): 16.3 Ultimate
* OS information: Windows 7 Enterprise
* Gauge IntelliJ plugin version: 0.2.1
* Does the project uses any Build tool(Gradle/Maven)? Ant
```
Run gauge -v on your system and paste the results here
```
Gauge version: 0.7.0

Plugins
-------
html-report (3.1.0)
java (0.6.1)
xml-report (0.2.0)

**Comment by kashishm** [comment]
@khagberg Could you please update gauge=0.8.3, gauge-java=0.6.2 and Gauge IntelliJ plugin=0.3.3 and then try

**Comment by khagberg** [comment]
Sorry, I'm relatively new to this. It appears the latest build is 0.8.1 not 0.8.3...

**Comment by kashishm** [comment]
@khagberg You can download the latest installers for your OS from [Gauge website](https://getgauge.io/get-started.html). It should have the links to 0.8.3 installers. Please hard reload the page if it shows 0.8.1

**Comment by khagberg** [comment]
Upgraded to 0.8.3 and latest plugin 0.3.3 and that seemed to have fixed the issue I was seeing. Thank you!
