### ISSUE TITLE
Issue with IntelliJ plugin and Ruby project

### ISSUE THREAD

**Issue by justinsako** [getgauge/Intellij-Plugin#241]
<!--
Thanks a lot for reporting issues to Gauge IntelliJ plugin! This is the issue tracker for reporting bugs or for requesting new feature and enhancements.

If you have any support related questions, please refer our documentation at http://getgauge.io/documentation/user/current/ide_support/intellij_idea.html. You can even ask questions on Google groups (http://groups.google.com/forum/#!forum/getgauge) or on gitter (https://gitter.im/getgauge/chat).

This is the issue tracker for Gauge IntelliJ plugin.

I have been playing with Gauge, created a ruby-based project and have been editing files with Atom.  The project seems to be functional, but when I tried to "Open" the project in IntelliJ IDEA 2017.1 (that I installed yesterday, along with the Ruby and Gauge plugins), it indicated that there was an error.

8:36 AM	Exception occurred in Gauge plugin
				Please log an issue here with the following details and reload the project.
				
				```
				/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- gauge_runtime (LoadError)
				[0m	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
					from -e:1:in `<main>'
				[0mRuby runner Failed. Reason: exit status 1
				[0mKilling Gauge daemon. Runner with pid 7699 quit unexpectedly(exit status 1).
				```
				* Idea version: 2017.1
				* API version: IU-171.3780.107
				* Plugin version: 0.3.3
				* Gauge version: 0.8.3

**Comment by sriv** [comment]
It is unclear what is the exact issue you're trying to highlight. In any case, the Intellij plugin does not work with Ruby project as it is designed to work with the Java type system.

Please feel free to add more details, and we can discuss.
