### ISSUE TITLE
Go to declaration is not working if spec folder is not in the root folder of project

### ISSUE THREAD

**Issue by mdolinin** [getgauge/Intellij-Plugin#242]
### Expected behavior
Go to declaration should work if specs folder is placed in other folder than root of project.

### Actual behavior
Go to declaration doesn't work if specs folder is placed in other folder than root of project.

### Steps to reproduce
1. Create project from gauge-archetype-java v1.1.0
2. Move `specs` folder to `src/test/resources`
3. Open spec file and try to use `Go to declaration` on any implemented step.

### Additional details
Also unimplemented steps is not highlighted.
And `Find usages` from step implementation, couldn't find steps.

### Version information

* IntelliJ IDEA 2017.1.1 Ultimate
* macOS Sierra 10.12.4
* Gauge IntelliJ plugin version 0.3.3
* Maven version 3.3.9
```
Run gauge -v on your system and paste the results here
Gauge version: 0.8.3

Plugins
-------
html-report (3.1.0)
java (0.6.2)
xml-report (0.2.0)
```

**Comment by jfock** [comment]
Same issue when using Gauge into a module of a Gradle project:

* IntelliJ CE 2017.2.4
* Gauge plugin 0.3.6

Can we expect a fix for that and/or is there a workaround?

**Comment by olegderid** [comment]
@BugDiver , please, confirm if there is tentative to take this bug for fix in next release?

**Comment by zabil** [comment]
@olegderid, unfortunately, there's a bit of work to get this working. We'll try to fix it in the next release. But the next release is not coming soon.

**Comment by imelnic555** [comment]
@zabil , Could you at least estimate when the fix will be available?

**Comment by xwinie** [comment]
Same issue when using Gauge into a module of a Gradle project:

IntelliJ Ultimate 2017.2.6
Gauge plugin 0.3.8

but maven is correct work!

**Comment by Borisakov** [comment]
Is there any estimated time for this issue?

**Comment by manuviswam** [comment]
Still not fixed

**Comment by nehashri** [comment]
related issue : #373

**Comment by Debashis9012** [comment]
This issue has been verified.
Observations:
1. Goto navigation/Declarations/Implementations are working fine.
2. Unimplemented steps are highlighting properly.
Based on the observations this issue has been fixed. Tested with the below nightly version
```v0.3.15.nightly-2019-04-11```
