### ISSUE TITLE
Seamless gauge installation via IDE

### ISSUE THREAD

**Issue by sriv** [getgauge/Intellij-Plugin#243]
### Expected behavior
When a Gauge project is opened in Intellij, in a machine that does not have Gauge executable installed, download and install latest Gauge executable, after asking for the user's consent.

### Actual behavior
When Gauge isn't installed, user is presented with a message indicating such.

---

### Dev Notes

- Best way to achieve this is to download the latest installer, and invoke it in silent mode. 

- Since this is invoked via Intellij, it is safe to assume that gauge-java plugin also needs to be installed.

**Comment by zabil** [comment]
Prompt the user before creating a new project for an option of what gauge executable to use.

## Download and install gauge per project
![newopen_project_gaugewrapper](https://cloud.githubusercontent.com/assets/54427/26244963/88e01594-3c81-11e7-9e1f-902400b53308.png)

This will download the gauge binary in the project `.gauge` project and create a `gaugew` wrapper script that can be used to manage gauge versions. The `gaugew` wrapper can be checked in to make this configuration portable.

## Use local Gauge distribution

![newopen_project_gauge_1](https://cloud.githubusercontent.com/assets/54427/26245048/e2af4e00-3c81-11e7-8f34-d5860fbf8e44.png)

The user can refer to an already installed version of gauge.

The configuration can be modified later via the project preferences page.

**Comment by mahendrakariya** [comment]
This is an awesome idea. But at the same time, I think we should cross check the JetBrains guidelines around installing something outside the IntelliJ ecosystem. In case of violation, the plugin maybe black listed and removed.

**Comment by zabil** [comment]
Sure will check.
This will work similar to how gradlew works on intellij. Although again the gradle plugin is officially supported by intellij.

**Comment by zabil** [comment]
This will be implemented in VS code.
