### ISSUE TITLE
Step with an * in the middle of the step definition results in a fatal IDE error

### ISSUE THREAD

**Issue by deepthigc** [getgauge/Intellij-Plugin#25]
Write a step - * Refactor "step 1" to "step 2"
Update/Change this to - * Refactor "step 1"* to "step2" (* introduced mid sentence)
This results in the following error. The spec file cannot be loaded in the IDE till the change in fixed

com.intellij.diagnostic.MessagePool$TooManyErrorsException: Too many IDE fatal errors. Monitoring stopped.

**Comment by prateekbaheti** [comment]
Fixed the issue for concept lexer as well. Not treating as comment but a valid step if multiple '*' found in a step name.
