### ISSUE TITLE
IntelliJ IDEA Gauge Plugin issue.

### ISSUE THREAD

**Issue by vibheeshk** [getgauge/Intellij-Plugin#250]
### Expected behavior
I should be able to work with my gauge project without showing any issues

### Actual behavior
It is throwing the following error:
Error: Could not find or load main class com.thoughtworks.gauge.GaugeRuntime
				process C:\Program Files\Java\jre1.8.0_112\bin\java.exe with pid 8256 quit unexpectedly. exit status 1
				Killing Gauge daemon. Runner with pid 8432 quit unexpectedly(exit status 1).

### Steps to reproduce
1. Install IntelliJ IDEA 64 bit application on 64 Bit machine
2. Install the Gauge plugin in the machine
3. Open the existing project in IntelliJ IDEA

### Version information

* IntelliJ version and edition(Community/Ultimate): 
* OS information:
* Gauge IntelliJ plugin version:
* Does the project uses any Build tool(Gradle/Maven)?
```
Run gauge -v on your system and paste the results here
```
Gauge version: 0.8.3

Plugins
-------
html-report (3.1.0)
java (0.6.2)
xml-report (0.2.0)

**Comment by kashishm** [comment]
@vibheeshk Please update Gauge to the latest version [0.8.4](https://github.com/getgauge/gauge/releases/tag/v0.8.4) and then try.

**Comment by sguptatw** [comment]
@vibheeshk - Closing this issue. If you face this issue again, please feel free to re-open
