### ISSUE TITLE
gauge plugin

### ISSUE THREAD

**Issue by onderdiri** [getgauge/Intellij-Plugin#251]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Version information

* IntelliJ version and edition(Community/Ultimate): 
* OS information:
* Gauge IntelliJ plugin version:
* Does the project uses any Build tool(Gradle/Maven)?
```
Run gauge -v on your system and paste the results here
```

**Comment by sriv** [comment]
Please give some details about the issues.

**Comment by onderdiri** [comment]
Hi,
I solved the issue. This errors source our company network and
websense fiter. Thanks for help.

2017-05-08 20:22 GMT+03:00 Srikanth <notifications@github.com>:
