### ISSUE TITLE
Gauge module not being detected

### ISSUE THREAD

**Issue by brown131** [getgauge/Intellij-Plugin#252]
### Expected behavior
The module defined as a gauge module should should the gauge icon and specs don't show green arrows next to the scenarios and specs.

### Actual behavior
I get an IDE error (sometimes). 

Gauge is becoming increasingly unstable. We spend way too much time twiddling projects to make it work as it's supposed to. I wish we hadn't written so many of unit tests using this tool given how crappy it's become.

### Steps to reproduce
1. Define a new Gauge module in IntelliJ
2. Watch it not work. Specs don't get arrows, so you can't run them. Gradle can't build the Java code in Gauge module. Worse even I get to, after closing the IDE it will fail again. 

### Version information

* IntelliJ version and edition(Community/Ultimate): 
* OS information: Windows 10
* Gauge IntelliJ plugin version: 0.3.3
* Does the project uses [sic] any Build tool(Gradle/Maven)?
Gradle

Run gauge -v on your system and paste the results here
Gauge version: 0.8.3

Plugins
-------
html-report (3.1.0)
java (0.6.2)
xml-report (0.2.0)

**Comment by zabil** [comment]
> Gauge is becoming increasingly unstable. We spend way too much time twiddling projects to make it work as it's supposed to. I wish we hadn't written so many of unit tests using this tool given how crappy it's become.

Well, this is in beta and we move fast and break things (for the better). If you check our commit logs you'll  see we've made massive changes/improvements across releases. We expect beta users to be invested in testing, reporting and taking a few risks to make this a great product.

If stability is important to you we suggest you wait for release 1.0. Until then, thanks for reporting this issue, We'll look at it.

**Comment by zabil** [comment]
https://github.com/getgauge/gauge/pull/640
