### ISSUE TITLE
Autoimport @Step while creating a new step implementation file.

### ISSUE THREAD

**Issue by nehashri** [getgauge/Intellij-Plugin#263]
While creating a new class @step annotation has to be imported. Instead import it by default.

**Comment by sguptatw** [comment]
Test cases
- [ ] should create a new file with import statement
- [ ] should work as expected even if there is a compilation error in the project
- [ ] should work as expected even if the file is empty.
- [ ] adding the step to existing class should continue to work.

**Comment by sguptatw** [comment]
Getting a null pointer exception
* Create an empty.java file. This file should be empty. 
* I choose to implement the step in the empty file.
* I am getting a null pointer exception

**Expected behavior**
Implementation on an empty file should be similar to a new file.

**Comment by Apoorva-GA** [comment]
- Empty java file is no more shown in the dropdown list of java files while implementing the step.
Fix is available in nightly : 0.3.4.nightly-2017-06-14
