### ISSUE TITLE
Can debug gauge scenario no more in the latest IntelliJ Idea 2017.2

### ISSUE THREAD

**Issue by jtonic** [getgauge/Intellij-Plugin#279]
### Expected behavior
Start a session debug for a gauge scenario

### Actual behavior
An exception is displayed and nothing happened.

### Steps to reproduce
1. Right click on the scenario line in specification
2. choose debug

#### Exception shown in the event log:
21:31	Error running 'This is a simple scenario (3)': com.intellij.execution.impl.RunManagerImpl.<init>(Lcom/intellij/openapi/project/Project;Lcom/intellij/ide/util/PropertiesComponent;)V

### Version information

IntelliJ IDEA 2017.2
Build #IU-172.3317.76, built on July 15, 2017
JRE: 1.8.0_152-release-915-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

* Gauge IntelliJ plugin version: 0.3.4
* Does the project uses any Build tool(Gradle/Maven)?
```maven
Run gauge -v on your system and paste the results here
```Gauge version: 0.8.3
Plugins
-------
html-report (3.1.0)
java (0.6.4)
spectacle (0.1.2)

**Comment by BugDiver** [comment]
Fix should be available in nightly >= 20-7-2017

**Comment by jtonic** [comment]
Hi,

I downloaded and install the nightly build and the debug issue vanished.

Thank you.
