### ISSUE TITLE
Multi Module Maven Java: Failed To Find Project Directory, Undefined Step, Arg Miscount, Deprecated

### ISSUE THREAD

**Issue by chriskellydev** [getgauge/Intellij-Plugin#282]
### Expected behavior
* Running tests within IntelliJ should not give a [DEPRECATED] message in the RUN dialog.
* Implemented steps within a specification should not appear *red* with the text "Undefined Step"
* IntelliJ should load up fine.
* It should not complain about implemented steps with parameters not containing the correct number of parameters when they do.

### Actual behavior
* You get a [DEPRECATED] printout in the RUN panel when running (due to running with `gauge --simple-console` instead of the new `gauge run`).
* Implemented steps show as undefined.
* IntelliJ loads up spamming `Error: Specification Preview: Failed to find project directory`
  * NOTE: If you do not have Spectacle installed (which I do not believe should be a requirement but that's out of scope you'll get spammed about that first).
* You receive an expected[0] actual[#] warning for implemented steps within a sub module.

### Steps to reproduce
1. IntelliJ > File > New > Project...
2. Maven > Next > *Fill Out Artifact/Group ID* > Next > *Fill Out Project Directory* > Finish
3. Open (root) pom.xml and add:
```
<modules>
    <module>gauge</module>
</modules>
```
4. Let IntelliJ do its magic and recognize/create the new `gauge` sub-module.
5. Fill out the pom.xml (gauge module) similar to the following:
```
    <parent>
        <groupId>parent</groupId>
        <artifactId>artifact</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>gauge</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.thoughtworks.gauge</groupId>
            <artifactId>gauge-java</artifactId>
            <version>0.6.4</version>
        </dependency>
    </dependencies>
```
6. Terminal your way to the gauge module directory and run `gauge init java`
7. Open the `example.spec` and bask in the red glow.

### Version information

* IntelliJ Version: IntelliJ IDEA Ultimate 2017.2
* OS: Fedora 24 (64 bit)
* Gauge IntelliJ Plugin Version: 0.3.5
* Maven Version: 3.3.9
```
Gauge version: 0.9.0

Plugins
-------
html-report (4.0.1)
java (0.6.4)
spectacle (0.1.2)
```

![gauge-intellij-full](https://user-images.githubusercontent.com/26169370/28640232-11084212-7219-11e7-95b9-727ac952f4c5.png)

![gauge-intellij-mismatch-args](https://user-images.githubusercontent.com/26169370/28640235-147e521a-7219-11e7-8b81-4e56f8264388.png)

![gauge-intellij-spam-spec-undefined](https://user-images.githubusercontent.com/26169370/28640240-17895590-7219-11e7-9160-16654af90dbe.png)

**Comment by kashishm** [comment]
> * You get a [DEPRECATED] printout in the RUN panel when running (due to running with `gauge --simple-console` instead of the new `gauge run`).

We have changed the `gauge` command structure. For backward compatibility, it will show these deprecated warnings.

> * IntelliJ loads up spamming `Error: Specification Preview: Failed to find project directory`

This looks like a bug and we are working on it. Follow #283 for more info on this.

>  * NOTE: If you do not have Spectacle installed (which I do not believe should be a requirement but that's out of scope you'll get spammed about that first).

`Preview` functionality requires `spectacle` to show spec in the browser. If you don't have that plugin then it will give you the option to install. With this, command line `gauge docs spectacle <specs>` and IntelliJ preview will be consistent and will have one implementation instead of two.

> * You receive an expected[0] actual[#] warning for implemented steps within a sub module.

Can you try reloading the project? It should work after that. This is because you initialized the gauge project via command line and the project was already opened in IntelliJ.

> * Implemented steps show as undefined.

I think it is because `src/test/java` is not marked as `sources root`.

**Comment by BugDiver** [comment]
> * IntelliJ loads up spamming `Error: Specification Preview: Failed to find project directory`

@chriskellydev We have released a new version of Gauge IntelliJ-Plugin. Could you please verify if this issue still exist ?

**Comment by chriskellydev** [comment]
I apologize for the late (and brief) reply. The warning/error spam is no longer occurring with the new 0.3.6 plugin version.

As an aside, I would like to bring notice to a still open [Issue #203](https://github.com/getgauge/Intellij-Plugin/issues/203) as that is actually the cause of my "Step Not Implemented" problem.

Thanks!
