### ISSUE TITLE
Refactoring not working

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#288]
**Expected behavior**
When there are no parse errors, I must be able to refactor

**Actual behavior**
* Refactor from the IDE is not working. However the command line refactoring is working fine.

**Steps to replicate**
* Create a basic gauge project using the IDE.
* Try refactoring `The word <word> has <expectedCount> vowels.` to `word <word> has <expectedCount> vowels.`
* Refactoring is failing even though there are no parse/compilation errors
`Error:Cannot perform refactoring: Unable to connect to runner.Runner with pid 21681 quit unexpectedly(exit status 1).`

**Version**
```
Gauge version: 0.9.0.nightly-2017-08-01

Plugins
-------
csharp (0.10.1)
html-report (4.0.1)
java (0.6.4)
ruby (0.4.1)
spectacle (0.1.2)
xml-report (0.2.0)
```
IDE - Version: 0.3.7.nightly-2017-07-28

**Comment by kashishm** [comment]
Fix is available in latest IntelliJ nightly 0.3.7.nightly-2017-08-18
