### ISSUE TITLE
Find usages of a step/concept

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#290]
**Expected behavior**
I should be able to find usages from IntelliJ

**Actual behavior**
Using the IntelliJ shortcut for find usages is not listing the usages

**Steps to replicate**
* Right click on a step/concept and find usages.
> Even though there are multiple usages it is not listing the usages.

**Version**
```
Gauge version: 0.9.0.nightly-2017-08-01

Plugins
-------
csharp (0.10.1)
html-report (4.0.1)
java (0.6.4)
ruby (0.4.1)
spectacle (0.1.2)
xml-report (0.2.0)
```
IDE - Version: 0.3.7.nightly-2017-07-28

**Comment by kashishm** [comment]
Fix is available in latest IntelliJ nightly 0.3.7.nightly-2017-08-18

**Comment by sguptatw** [comment]
This works for steps with implementation. What should be the behavior for an unimplemented step? Shouldn't all the usages be listed?

**Comment by kashishm** [comment]
@sguptatw There is already an issue for that https://github.com/getgauge/Intellij-Plugin/issues/46.
