### ISSUE TITLE
Getting the implementation method suggestion on IDE

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#293]
**Expected behavior**
It should not show these suggestions on IDE

**Actual behavior**
Getting the message on the IDE

**Steps to replicate**
* run the specs
[untitled 2.zip](https://github.com/getgauge/Intellij-Plugin/files/1266062/untitled.2.zip)

**Version**
```
Gauge version: 0.9.2.nightly-2017-08-30
Commit Hash: b0fda9f

Plugins
-------
csharp (0.10.1)
java (0.6.5.nightly-2017-08-29)
ruby (0.4.1)
spectacle (0.1.2)
xml-report (0.2.0)
```
IDE - Version: 0.3.7.nightly-2017-08-30

**Comment by BugDiver** [comment]
Fix should be available in nightly >= 31-08-2017
