### ISSUE TITLE
Update Gauge Commands

### ISSUE THREAD

**Issue by nehashri** [getgauge/Intellij-Plugin#299]
As of Gauge version 0.9.0, the gauge command structure has been updated. Intellij plugin should use latest Gauge commands.

If an older version of Gauge is installed, gauge daemon will not be started. An error message should be shown indicating this.

**Comment by nehashri** [comment]
Should be available in intellij plugin nightly >= 16-10-2017

**Comment by sguptatw** [comment]
Test cases
- [x] Open a gauge project
- [x] autocomplete step
- [x] refactor step
- [x] step implementation
- [x] code navigation
- [x] specs folder execution
