### ISSUE TITLE
 Individual spec and scenario details of the run are not getting displayed in the test runner

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#301]
**Expected behavior**
The test runner should show the execution details at the spec and scenario level

**Actual behavior**
 Individual spec and scenario details of the run are not getting displayed in the test runner

**Steps to replicate**
* Click on the scenario/spec name in the test runner tab after executing a spec.

**Version**
```
Gauge version: 0.9.4

Plugins
-------
csharp (0.10.2.nightly-2017-10-09)
html-report (4.0.2)
java (0.6.6.nightly-2017-09-14)
js (2.0.3)
ruby (0.4.2)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)
```
IntelliJ - Version: 0.3.8.nightly-2017-10-16

**Comment by nehashri** [comment]
@sguptatw The expected behaviour in the test runner is to show details of run only in case of a failure. On success nothing will be shown.
