### ISSUE TITLE
Incompatibilities with Intellij 2017.3 EAP (173.x)

### ISSUE THREAD

**Issue by elleuca** [getgauge/Intellij-Plugin#304]
### Expected behavior
Gauge intellij-plugins should work with upcoming Intellij 2017.3 release (ver 173.x) :-)

### Actual behavior
Updating from Intellij Idea 2017.2.x to 2017.3 EAP gauge plugin is downgraded from 0.3.8 to 0.3.4 (same versione installing plugin from fresh). See compatible builds in https://plugins.jetbrains.com/plugin/7535-gauge  

After downgrade, opening a gauge-base project "Gauge API non started" exception occurs (probably because I've latest gauge 0.9.x installed)

### Steps to reproduce
1. Install Intellij gauge plugin on Intelllij 2017.2 version
2. Switch to Intellij 2017.3 EAP or Public preview

### Version information

* IntelliJ version and edition: Ultimate, updated from 2017.2.x to 2017.3 EAP 173.3415.22
* OS information: macOS 10.13.1
* Gauge IntelliJ plugin version: 0.3.8 before update, 0.3.4 after
* Does the project uses any Build tool? gradle
```
Gauge version: 0.9.4

Plugins
-------
flash (0.0.1)
html-report (4.0.2)
java (0.6.5)
screenshot (0.0.1)
spectacle (0.1.2)
```

**Comment by jtonic** [comment]
I noticed that for the GA version of IntelliJ Idea 2017.3 the gauge version 0.3.4 is shown as available for installation. Is this an issue in latest version of intellij idea or is smth in the gauge plugin?

Thank you.

**Comment by jtonic** [comment]
Moreover, I tried to install the 0.3.8 from disk and Idea (2017.3) complains it is not compatible with this installation.

**Comment by sguptatw** [comment]
@jtonic: 
Kindly check with the following
Gauge version - gauge 0.9.6
Gauge Intellij Plugin 0.3.9.
