### ISSUE TITLE
Null pointer exception occurs when executing the spec

### ISSUE THREAD

**Issue by rabiamarzhiya** [getgauge/Intellij-Plugin#306]
### Expected behavior
Spec should run without any exception
### Actual behavior
Spec when running shows null pointer exception

### Steps to reproduce
1. Use intellij and load a gauge project
2. Run the spec file
3. Observe the results

### Version information

* IntelliJ version and edition(Community/Ultimate): Community # IC-172.4574.11
* OS information: Linux 16.04 (ubuntu)
* Gauge IntelliJ plugin version: 
* Does the project uses any Build tool(Gradle/Maven)? : No
```
Gauge version: 0.9.5
Commit Hash: 51cfe8d

Plugins

html-report (4.0.2)
java (0.6.5)
js (2.0.0)
screenshot (0.0.1)
spectacle (0.1.2)

Gauge Plugin version: 0.3.8

```

Error that I get is as follows:

Message: java.lang.NullPointerException
Stack Trace:
platform_e2e.PlatformObjects.userName(PlatformObjects.java:25)
platform_e2e.PlatformActions.login(PlatformActions.java:155)
platform_e2e.PlatformActions.loginSuccess(PlatformActions.java:142)
platform_e2e.registerSteps.loginValid(registerSteps.java:98)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
com.thoughtworks.gauge.execution.MethodExecutor.execute(MethodExecutor.java:38)
com.thoughtworks.gauge.execution.StepExecutionStage.executeStepMethod(StepExecutionStage.java:74)
com.thoughtworks.gauge.execution.StepExecutionStage.executeStep(StepExecutionStage.java:67)
com.thoughtworks.gauge.execution.StepExecutionStage.execute(StepExecutionStage.java:49)
com.thoughtworks.gauge.execution.AbstractExecutionStage.executeNext(AbstractExecutionStage.java:24)
com.thoughtworks.gauge.execution.HookExecutionStage.execute(HookExecutionStage.java:43)
com.thoughtworks.gauge.execution.ExecutionPipeline.start(ExecutionPipeline.java:29)
com.thoughtworks.gauge.processor.ExecuteStepProcessor.process(ExecuteStepProcessor.java:39)
com.thoughtworks.gauge.connection.MessageDispatcher.dispatchMessages(MessageDispatcher.java:91)
com.thoughtworks.gauge.GaugeRuntime.dispatchMessages(GaugeRuntime.java:105)
com.thoughtworks.gauge.GaugeRuntime.access$100(GaugeRuntime.java:37)
com.thoughtworks.gauge.GaugeRuntime$2.run(GaugeRuntime.java:86)
java.lang.Thread.run(Thread.java:748).

Kindly help

**Comment by Apoorva-GA** [comment]
Could you please share a sample project where you are facing the above issue.

**Comment by Apoorva-GA** [comment]
Looks like the null pointer is occurring in the step implementation. Please have look at your step implementations.

**Comment by sguptatw** [comment]
Closing this issue as the exception is in the step implementation and not gauge execution.
