### ISSUE TITLE
Unsupported Gauge Version: This version of Gauge Intellij plugin only works with Gauge version >= 0.9.0

### ISSUE THREAD

**Issue by akshaypanambur** [getgauge/Intellij-Plugin#307]
Getting "Unsupported Gauge Version: This version of Gauge Intellij plugin only works with Gauge version >= 0.9.0" error when trying to create a project using gauge plugin.

Below is my Gauge version

**Gauge version: 0.9.5**
Commit Hash: 51cfe8d

Plugins
-------
html-report (4.0.2)
java (0.6.5)
screenshot (0.0.1)

Intellij Gauge Plugin version : 0.3.8
Intellij Version: 2017.2.6

**Comment by Apoorva-GA** [comment]
Please check the what `Gauge binary path` is set to in intellij.
You can find it in `Preferences->Tools->Gauge`.

Make sure you set it to gauge binary >= 0.9.0.

**Comment by akshaypanambur** [comment]
Thanks it worked fine! There was mis-entered value in Gauge binary path

**Comment by michael-edgar** [comment]
I'm having the same issue now running on Ubuntu 18.04.3 with the following:
Gauge version: 1.0.6, 
Commit Hash: 2bc49db, 
html-report (4.0.8),
java (0.7.2), 
screenshot (0.0.1) 

As for intellij: Intellij IDEA Ultimate 2019.2 
Gauge plugin 0.3.16

I've logged this issue on stackoverflow (https://stackoverflow.com/questions/57560088/unsupported-gauge-version-this-version-of-gauge-intellij-plugin-only-works-with)
Check there for any other details
