### ISSUE TITLE
principal class not found com.thoughtworks.gauge.GaugeRuntime

### ISSUE THREAD

**Issue by ahewstone** [getgauge/Intellij-Plugin#313]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Version information

* IntelliJ version and edition(Community/Ultimate): 
* OS information:
* Gauge IntelliJ plugin version:
* Does the project uses any Build tool(Gradle/Maven)?
```
Run gauge -v on your system and paste the results here
```

**Comment by sguptatw** [comment]
@ahewstone : Please fill the above template with details of the issue you are facing.

**Comment by sriv** [comment]
closing as stale.
