### ISSUE TITLE
Gauge API not started

### ISSUE THREAD

**Issue by Borisakov** [getgauge/Intellij-Plugin#316]
### Expected behavior
Gauge plugin for IntelliJ should start and work.

### Actual behavior
I am getting an exception on the plugin startup.

### Steps to reproduce
1. Install Gauge plugin  
2. Restart IntelliJ

### Event log
[log.txt](https://github.com/getgauge/Intellij-Plugin/files/1758678/log.txt)

### Version information

IntelliJ IDEA 2018.1 EAP (Community Edition)
Build #IC-181.3870.7, built on February 20, 2018
JRE: 1.8.0_152-release-1136-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
* Gauge IntelliJ plugin version: 0.3.4
* The project uses a Build tool - Gradle

Gauge version: 0.9.5
Commit Hash: 51cfe8d

Plugins
-------
flash (0.0.1)
html-report (4.0.3)
java (0.6.6)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.0)

**Comment by nehashri** [comment]
@Borisakov Looks like you have an older version of Gauge Intellij Plugin. Gauge plugin version 0.3.4 does not work well with the latest Intellij version. Please do update you plugin and try again.

PS: You can also consider updating Gauge.

**Comment by Borisakov** [comment]
@nehashri Hi, I am trying to install the plugin manually (0.3.9) using "Install plugin from disk.." and I am getting 
![image](https://user-images.githubusercontent.com/34122721/36717133-8d1b5a20-1ba5-11e8-8537-cb5541f5c617.png)

**Comment by nehashri** [comment]
@Borisakov We don't support Intellij EAP versions yet. The current plugin is compatible only with Intellij versions 2017.* . The plugin works well with latest stable version of Intellij.

**Comment by Borisakov** [comment]
@nehashri It works. Thanks.
