### ISSUE TITLE
java.lang.RuntimeException: Gauge API not started

### ISSUE THREAD

**Issue by tangshunfa** [getgauge/Intellij-Plugin#319]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Version information

* IntelliJ version and edition(Community/Ultimate): 
* OS information:
* Gauge IntelliJ plugin version:
* Does the project uses any Build tool(Gradle/Maven)?
```
Run gauge -v on your system and paste the results here
```

**Comment by sriv** [comment]
Please fill in some detail on when this occurs, for us to investigate. Thanks.

**Comment by sguptatw** [comment]
Closing this as there are no details about the issue. Please feel free to re-open this after adding the details.
