### ISSUE TITLE
com.intellij.openapi.module.impl.ModuleManagerComponent@548c528c: Gauge API not started

### ISSUE THREAD

**Issue by Doraliangbo** [getgauge/Intellij-Plugin#328]
com.intellij.openapi.module.impl.ModuleManagerComponent@548c528c: Gauge API not started

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1. install the latest intellij 2018.1 and the latest gauge plugin 0.3.11
2. launch the IntelliJ 
3.observe the error code

### Version information

* IntelliJ version and edition(Community/Ultimate): community 2018.1
* OS information:high Sierra
* Gauge IntelliJ plugin version:0.3.11

**Comment by nehashri** [comment]
@Doraliangbo Can you provide gauge version you are using. Run `gauge -v` from command line and paste the contents here.

**Comment by Doraliangbo** [comment]
The version is 0.9.4

**Comment by v-mwalk** [comment]
Same as OP.  Didnt want to create a new issue.  I cannot create a Gauge project in IntiliJ.  Creating a new prokecy just shows the **Error adding module to project: Gauge API not started** error.

**Comment by sguptatw** [comment]
Can you please try with [latest Gauge version](https://github.com/getgauge/gauge/releases), [Gauge-IntelliJ](https://github.com/getgauge/Intellij-Plugin/releases) and [Gauge-Java](https://github.com/getgauge/gauge-java/releases) and let us know if the issue is resolved.

**Comment by v-mwalk** [comment]
Tried with (x86-64) Gauge 0.9.9, Gauge-IntelliJ 0.3.11 and Gauge-Java 0.6.7.

All good - can create Gauge project and Can add specs to non-Gauge projects.

Thanks
