### ISSUE TITLE
Changing name of parameter during refactor fails to update implementation

### ISSUE THREAD

**Issue by deepthigc** [getgauge/Intellij-Plugin#33]
````
Execute tests with "parallel" and specification "refactor"
````

Shift + F6 on a step
Update the name of the parameter from <tag name> to <tag>, this has the following effect on the step but it does not change the annotation/implementation. The annotation should be changed to reflect the new param.

````
Execute tests with "" and specification "refactor"
````

**Comment by prateekbaheti** [comment]
Decided that this is expected behaviour. The changed value is treated as a deletion of the existing parameter and addition of a new parameter.
