### ISSUE TITLE
Exception occures when open another gauge-maven project

### ISSUE THREAD

**Issue by lchrennew** [getgauge/Intellij-Plugin#336]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1. Open an gauge maven project in IDEA
2. Open another gauge maven project in the same window or a new window
3. See event log
### IDEA Event Log:
2018/6/21
13:22	Exception occurred in Gauge plugin
		Please log an issue here with the following details and reload the project.
		
		```
		Gauge daemon initialized and listening on port: 4798
		```
		* Idea version: 2018.1.5
		* API version: IU-181.5281.24
		* Plugin version: 0.3.11
		* Gauge version: 0.9.9
### Version information

* IntelliJ version and edition(Community/Ultimate): Ultimate
* OS information: Windows
* Gauge IntelliJ plugin version: latest
* Does the project uses any Build tool(Gradle/Maven)? Maven
```
Run gauge -v on your system and paste the results here
Gauge version: 0.9.9
Commit Hash: 8db625f

Plugins
-------
html-report (4.0.4)
java (0.6.8)
screenshot (0.0.1)
spectacle (0.1.2)
```

**Comment by lchrennew** [comment]
the problem is still

**Comment by NivedhaSenthil** [comment]
can you give more details about what problem exactly happens ?

**Comment by BugDiver** [comment]
@lchrennew I'm closing this issue for now. Feel free to reopen with details if the issue still exists.
