### ISSUE TITLE
Gauge plugin causes IntelliJ to start with errors

### ISSUE THREAD

**Issue by gagneet** [getgauge/Intellij-Plugin#341]
### Expected behavior
Gauge plugin should work

### Actual behavior
Error is shown:

```
					Error ----------------------------------
					
					Unable to set working directory : mkdir C:\Users\gagneet\OneDrive\documents\work\gauge\cc: Cannot create a file when that file already exists.
					
					Get Support ----------------------------
						Docs:          https://docs.gauge.org
						Bugs:          https://github.com/getgauge/gauge/issues
						Chat:          https://gitter.im/getgauge/chat
					
					Your Environment Information -----------
						windows, 1.0.0, 5a99965
						html-report (4.0.4), java (0.6.8), screenshot (0.0.1)
					```
					* Idea version: 2018.1.6
					* API version: IU-181.5540.7
					* Plugin version: 0.3.11
					* Gauge version: 1.0.0

### Steps to reproduce
1.
2.
3.

### Version information

* IntelliJ version and edition(Community/Ultimate): Ultimate
* OS information: Windows 10 1803
* Gauge IntelliJ plugin version: 3.11
* Does the project uses any Build tool(Gradle/Maven)?
No
Run gauge -v on your system and paste the results here
Gauge version: 1.0.0
Commit Hash: 5a99965

Plugins
-------
html-report (4.0.4)
java (0.6.8)
screenshot (0.0.1)

**Comment by gagneet** [comment]
I am encountering this when I open an IntelliJ project created with Gauge template.


Steps:

1. Create new project, using Gauge
2. Make changes to the project and add source files
3. Files are stored on OneDrive (project folder created and stored within OneDrive)
4. Close the project
5. Reopen the project 
6. The above error is reported.

Also, the Gauge installation was done to c:\windows\system32
Expand-Archive -Path gauge-1.0.0-windows.x86_64.zip -DestinationPath C:\Windows\System32

This is on a personal laptop with Windows 10 (1803) installed and the login user is an Administrator

**Comment by sriv** [comment]
Hi,

I installed gauge using what you mentioned:

```
 Expand-Archive -Path gauge-1.0.0-windows.x86_64.zip -DestinationPath C:\Windows\System32
```

Created a new project using the gauge intellij plugin template and reloaded the project. Works for me.

Could you please help with below:

- try using a location that is in the local system (i.e. not OneDrive's folder)
- if possible could you share a sample project where you see this error? I'd like to verify if the issue is project related for environment related.

thanks.

**Comment by gagneet** [comment]
Seems there is an issue with integration to OneDrive files.
