### ISSUE TITLE
Should be able to run maven project specifications from IDE

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#348]
**Expected behavior**

**Actual behavior**
Getting the following error
```
Failed to start gauge API: Runner with pid 381748 quit unexpectedly(exit status 1).

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
	windows, 1.0.1.nightly-2018-08-08, 5652ab5
	dotnet (0.1.1), html-report (4.0.5), java (0.6.9), js (2.3.2), ruby (0.5.2), screenshot (0.0.1), xml-report (0.2.1)"}

Process finished with exit code 1
```
**Steps to replicate**
* Checkout [gauge-tests](https://github.com/getgauge/gauge-tests) into a new folder http://github.com/getgauge/gauge-tests
* Open the project in the IDE
* Run a scenario from the IDE
> Getting the above error

Blocks #342

**Comment by sguptatw** [comment]
Still getting the same error when executing from the IDE.

<img width="1076" alt="screen shot 2018-09-12 at 10 57 18 am" src="https://user-images.githubusercontent.com/6310197/45404009-daec8880-b67a-11e8-8c03-17607a121e80.png">

Steps to replicate - same as the original issue

**Version**
```
Gauge version: 1.0.2.nightly-2018-09-11
Commit Hash: 4060f37

Plugins
Gauge-Maven-Java - 0.6.9.nightly-2018-09-03
Gauge-IntelliJ plugin version - Sep 11 2018 nightly
```

**Comment by BugDiver** [comment]
@sguptatw  I'm not able to replicate. 
Could you please verify?

**Comment by sguptatw** [comment]
Working as expected
```
Gauge version: 1.0.3.nightly-2018-10-05
Commit Hash: ff2114f

Plugins
-------
html-report (4.0.6.nightly-2018-08-13)
java (0.6.9.nightly-2018-09-27)
```
Gauge IntelliJ - Version: 0.3.13.nightly-2018-09-14
