### ISSUE TITLE
1

### ISSUE THREAD

**Issue by AnastasiiaSelianko** [getgauge/Intellij-Plugin#350]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Version information

* IntelliJ version and edition(Community/Ultimate): 
* OS information:
* Gauge IntelliJ plugin version:
* Does the project uses any Build tool(Gradle/Maven)?
```
Run gauge -v on your system and paste the results here
```

**Comment by nehashri** [comment]
@AnastasiiaSelianko Give us details on the issue you are facing.
