### ISSUE TITLE
plugin crashed while switching project to other non gauge project

### ISSUE THREAD

**Issue by nitink007** [getgauge/Intellij-Plugin#355]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Version information

* IntelliJ version and edition(Community/Ultimate): 
* OS information:
* Gauge IntelliJ plugin version:
* Does the project uses any Build tool(Gradle/Maven)?
```
Run gauge -v on your system and paste the results here
```

**Comment by shubhamsc** [comment]
@nitink007 Can you tell us more about the issue 
* How can replicate the issue?
* Which gauge plugin are you using?
* what is your gauge and plugin version?

**Comment by BugDiver** [comment]
@nitink007  I'm closing this issue. Please feel free to reopen it with required details, if you are still having this issue.
