### ISSUE TITLE
Should recognize Gauge installed using npm

### ISSUE THREAD

**Issue by sguptatw** [getgauge/Intellij-Plugin#356]
**Expected behavior**
Should recognize Gauge installed using npm

**Actual behavior**
The IDE does not recognize Gauge installed using npm

**Steps to replicate**
> Observed on Windows
* Ensure all gauge versions are uninstalled
* npm install @getgauge/cli -g
* Open a gauge-java project in IntelliJ

**Version**
```
Gauge-IntelliJ 0.3.13.nightly-2018-09-14
```

**Comment by sriv** [comment]
as a workaround, one can set the gauge binary path in the settings, under `Tools->Gauge`
