### ISSUE TITLE
getgauge/Intellij-Plugin

### ISSUE THREAD

**Issue by ngamage** [getgauge/Intellij-Plugin#361]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Version information

* IntelliJ version and edition(Community/Ultimate): 
* OS information:
* Gauge IntelliJ plugin version:
* Does the project uses any Build tool(Gradle/Maven)?
```
Run gauge -v on your system and paste the results here
```

**Comment by BugDiver** [comment]
@ngamage  I'm closing the issue since it does not have any information. Please feel free to open an issue with details if you are facing any.
