### ISSUE TITLE
External dependency issue when not using IntelliJ TestRunner

### ISSUE THREAD

**Issue by pvskarps** [getgauge/Intellij-Plugin#362]
I'm seeing what appears to be classpath issues with Gauge when I try to run a spec in IntelliJ when the IntellIJ Gauge plugin is set to NOT use the IntelliJ test runner.  If we run through the test runner then everything is fine.

We are experiencing this with our Gradle gauge project and I've been able to reproduce it on the getgauge-examples/java-gradle-selenium project (https://github.com/getgauge-examples/java-gradle-selenium)

### Expected behavior
Spec runs as expected

### Actual behavior
Specs fail to execute due to classpath issues with external dependencies when no running through the IntelliJ test runner.
The following is a shortened version of the output from the getgauge-examples/java-gradle-selenium project when running user.spec through the IntelliJ TestRunner is disabled:

C:\Users\MTQA\GaugeExe\gauge.exe run --simple-console C:/Users/MTQA/GaugeTest/java-gradle-selenium/specs/user.spec
src\main\java\com\thoughtworks\gauge\example\pages\CreateProductPage.java:3: error: package org.openqa.selenium does not exist
import org.openqa.selenium.WebElement;
                          ^
src\main\java\com\thoughtworks\gauge\example\pages\CreateProductPage.java:8: error: cannot find symbol
    public WebElement product_title;
           ^
  symbol:   class WebElement
  location: class CreateProductPage
src\main\java\com\thoughtworks\gauge\example\pages\CreateProductPage.java:10: error: cannot find symbol
    public WebElement product_description;
           ^
  symbol:   class WebElement
  location: class CreateProductPage
src\main\java\com\thoughtworks\gauge\example\pages\CreateProductPage.java:12: error: cannot find symbol
    public WebElement product_author;
           ^
  symbol:   class WebElement
  location: class CreateProductPage

### Steps to reproduce
1. Use IntelliJ 2018.3 and Gauge Intellij Plugin 0.3.14
2. Clone getgauge-examples/java-gradle-selenium project (I know it is deptricated but it does a good job of showing the issue). 
3. Open the project in IntelliJ
4. Open File-Settings->Tools->Gauge and uncheck "Use IntelliJ test runner UI for execution"
5. Run user.spec and you will see the external dependency issues

### Version information

* IntelliJ version and edition(Community/Ultimate): 2018.3.1 Ultimate
* OS information: Windows 7
* Gauge IntelliJ plugin version: 1.0.3
* Does the project uses any Build tool(Gradle/Maven)? Gradle

Plugins
-------
html-report (4.0.6)
java (0.6.9)
screenshot (0.0.1)
xml-report (0.2.0)

**Comment by pvskarps** [comment]
By the way this issue doesn't exist in 0.3.12 of the plugin.

**Comment by Apoorva-GA** [comment]
Thanks for the update.
Note : the latest gauge intellij-plugin is [0.3.14](https://github.com/getgauge/Intellij-Plugin/releases/tag/v0.3.14). Please consider updating to the latest.

Closing this for now. Let us know if you face this issue again.
