### ISSUE TITLE
Just starting Intellij

### ISSUE THREAD

**Issue by kyriosdata** [getgauge/Intellij-Plugin#364]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Version information

* IntelliJ version and edition(Community/Ultimate): 
* OS information:
* Gauge IntelliJ plugin version:
* Does the project uses any Build tool(Gradle/Maven)?
```
Run gauge -v on your system and paste the results here
```

**Comment by Apoorva-GA** [comment]
Could you give us more info?
Please fill the details of the above template.

**Comment by Apoorva-GA** [comment]
Closing this issue. Please feel free to reopen if you find the details.
