### ISSUE TITLE
any plans to support python projects in intellij or pycharm?

### ISSUE THREAD

**Issue by delmaamoun** [getgauge/Intellij-Plugin#366]
I'm using pycharm as the main IDE for python tests, and it would be great to either have a plugin for pycharm or have the intellij plugin support pycharm, that would be awesome!

**Comment by zabil** [comment]
Ah yes. I see feedback and bug reports!

IntelliJ plugins are hard to develop and cumbersome run, test and debug :( 

There will be a plugin for Intellij when it supports the [Language server protocol](https://github.com/Microsoft/language-server-protocol).
