### ISSUE TITLE
Feature request: support javascript step implements

### ISSUE THREAD

**Issue by lchrennew** [getgauge/Intellij-Plugin#367]
Hi, there!

I am working on a Taiko ATDD project with gauge, I am used to writing specs and Java step implements in IDEA, but it seem this IDE plugin does not support Javascript step implements (it tips steps have not been implemented).
And an alternative solution is switching to VSCode, but I prefer using IDEA...
I want javascript implements to be supported in IDEA plugin.

**Comment by sriv** [comment]
some context [here](https://github.com/getgauge/Intellij-Plugin/issues/119)

//cc @zabil

**Comment by zabil** [comment]
We love Intellij IDEA too. 
However writing and maintaining plugins for IntelliJ idea is not easy :(

IntelliJ does not support [Language Server Protocol](https://discuss.kotlinlang.org/t/any-plan-for-supporting-language-server-protocol/2471).

A Javascript plugin will be available once IntelliJ adds LSP support.

**Comment by lchrennew** [comment]
> [Language Server Protocol](https://discuss.kotlinlang.org/t/any-plan-for-supporting-language-server-protocol/2471).

There’s a plugin for IntelliJ IDEA that allows it to act as a client for a Language Server Protocol server: https://github.com/gtache/intellij-lsp 147

**Comment by zabil** [comment]
Last time I checked. It didn't work.
You can try installing it configuring the following command in the settings.

```
gauge daemon --lsp
```

**Comment by kgalli** [comment]
@zabil can you explain what the difference is for having the gauge plugin playing nice with `Java` but not with `Javascript`. I'm completely new to IntelliJ IDEA plugins but I do not mind getting my hands dirty and implement what is necessary.

Let's assume it can be implemented with a reasonable amount of effort. How likely is it that a new version of IntelliJ will force an update of the plugin? From my point of view, the "only" broken part with the javascript is that it is not recognizing the step definitions. Solving this would already bring huge benefits. Can you give me some directions what I can do to implement it?

**Comment by zabil** [comment]
@kgalli thanks for reaching out!
Writing, testing or maintaining IntelliJ plugins has been quite tough in our experience. This is because of the plugin architecture. Have you tried Gauge's VS Code plugin? It has great support for Javascript.

However, I understand that switching IDE's may be difficult. There's documentation about how the Gauge IntelliJ plugin works at https://github.com/getgauge/Intellij-Plugin/wiki you can use this as a starting point.

**Comment by kgalli** [comment]
@zabil thanks. I will have a look. I tried the Gauge SS Code plugin and it is indeed very nice. Let's see what my opinions are once I really understand the effort which has to be invested to get the Intellij-Plugin properly working with Javascript. :-D
