### ISSUE TITLE
Exception occurred in Gauge Plugin

### ISSUE THREAD

**Issue by ashoktesting1982** [getgauge/Intellij-Plugin#369]
This is the issue tracker for Gauge IntelliJ plugin.

Exception occurred in Gauge Plugin, Please advise!!

* Idea version: 2018.2.2
* API version: IC-182.4129.33
* Plugin version: 0.3.14
**Gauge Version:**
Gauge version: 1.0.4
Commit Hash: 3a9a647
**Plugins**
html-report (4.0.5)
java (0.6.2)
spectacle (0.1.3)
xml-report (0.2.0)

**Comment by sriv** [comment]
Can you please share some details on what exception occured and any steps to replicate it? 

Thanks

**Comment by ashoktesting1982** [comment]
While Building the project I got this message in Intellij.
28/01/2019
11:51	Exception occurred in Gauge plugin
			Please log an issue here with the following details and reload the project.
			
			```
			Gauge daemon initialized and listening on port: 54037
			```
			* Idea version: 2018.2.2
			* API version: IC-182.4129.33
			* Plugin version: 0.3.14
			* Gauge version: 1.0.4

**Comment by sriv** [comment]
Some followup questions:

- Are you using any build tools (gradle/maven)? If so, what version of `gauge-java` do they have?
- Are there any details available in the `logs`? 
- Is there any project that we can try replicating this issue on?

Thanks

**Comment by ashoktesting1982** [comment]
I am using maven project, 
<dependency>
        <groupId>com.thoughtworks.gauge</groupId>
        <artifactId>gauge-java</artifactId>
        <version>0.6.9</version>
        <scope>test</scope>
    </dependency>

NOTE: I am going to update my java plugins and try the same.

I am able to build and run the specs, its just I got the above issue while building first time. I am using the sample project (Vowel Counts).

**Comment by ashoktesting1982** [comment]
Update to Intellij 2018.3.3 and Updated gauge latest versions (gauge-1.0.3, java-0.6.9) and now I am able to build and run project. Closing this Issue.
