### ISSUE TITLE
HTML preview gives file doesn't exists error.

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/Intellij-Plugin#372]
### Expected behavior
Should open the spec file in browser.
### Actual behavior
Shows that the ../$specfile.html doesn't exists.

### Steps to reproduce
1. Open spec file in intellij
2. right click-> open in browser

### Version information

* IntelliJ version and edition(Community/Ultimate): 2018.1
* OS information:mac 10.14.2
* Gauge IntelliJ plugin version: 0.3.15.nightly-2019-02-07
* Does the project uses any Build tool(Gradle/Maven)? no
```
Run gauge -v on your system and paste the results here
```
Gauge version: 1.0.5
Commit Hash: 6971850

Plugins
-------
html-report (4.0.8.nightly-2019-02-08)
java (0.7.1.nightly-2019-02-08)
js (2.3.4)
screenshot (0.0.1)
spectacle (0.1.2)
xml-report (0.2.1)

**Comment by Debashis9012** [comment]
Not able to reproduce it with the below version:
``` * Gauge IntelliJ plugin version: v0.3.15.nightly-2019-02-07```
```
Gauge version: 1.0.5.nightly-2019-02-15
Commit Hash: 48d032f

Plugins
-------
dotnet (0.1.1.nightly-2019-01-29)
html-report (4.0.7)
java (0.7.2.nightly-2019-02-12)
js (2.3.4.nightly-2018-12-20)
python (0.3.5.nightly-2019-02-04)
ruby (0.5.2.nightly-2019-01-28)
screenshot (0.0.1)
spectacle (0.1.4.nightly-2018-12-04)
xml-report (0.2.2.nightly-2019-01-11)
```
