### ISSUE TITLE
Support IntelliJ 2019.1

### ISSUE THREAD

**Issue by elleuca** [getgauge/Intellij-Plugin#376]
After updating intellij to latest stable (2019.1), gauge plugin downgrades to old 0.3.4 release

<img width="800" alt="Screenshot 2019-03-28 at 10 38 44" src="https://user-images.githubusercontent.com/1573759/55147136-21509300-5146-11e9-8ac4-0dff19374201.png">

### Actual behavior
Updated gauge plugin :-)

### Version information

* IntelliJ version and edition(Community/Ultimate): 2019.1 both community and ultimate
* OS information: macOS X 10.14
* Gauge IntelliJ plugin version: 0.3.14
```
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
flash (0.0.1)
html-report (4.0.7)
java (0.7.1)
js (2.3.4)
python (0.3.5)
screenshot (0.0.1)
```

**Comment by shubhamsc** [comment]
@elleuca I added new IntelliJ idea version in IntelliJ-plugin. 
We will release soon a new version of the plugin with the fix.
For now, you can install with [nightly](https://github.com/getgauge/Intellij-Plugin/#installing-nightly) from [zip file](https://bintray.com/gauge/Gauge-Java-Intellij/Nightly)

**Comment by Debashis9012** [comment]
As a work around we can install the nightly version of intellij plugin ``` v0.3.15.nightly-2019-04-01 ``` in intellij ```2019.1 version``` which works fine.
