### ISSUE TITLE
Gauge issue

### ISSUE THREAD

**Issue by pevniacik** [getgauge/Intellij-Plugin#385]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Version information

* IntelliJ version and edition(Community/Ultimate): 
* OS information:
* Gauge IntelliJ plugin version:
* Does the project uses any Build tool(Gradle/Maven)?
```
Run gauge -v on your system and paste the results here
```

**Comment by nehashri** [comment]
@pevniacik  Can you provide more details please.
