### ISSUE TITLE
Release tasks 0.3.16

### ISSUE THREAD

**Issue by Apoorva-GA** [getgauge/Intellij-Plugin#389]
These are the release activities to be performed when releasing Intellij plugin.
## Pre release
- [x] Check all commits that has been added with this release and make sure the relevant issues are tested/closed.
- [x] Update plugin.xml to include change notes for this release.
- [x] Check if all relevant tests are passing.
- [x] Take a call on release.

## Release
- [x] Trigger the Intellij release stages.
- [x] Make a note of all external contributors and add thank you note in release notes
- [x] Review the release notes and publish it.

## Post release
- [x] Send release mail to google groups.
- [x] Bump up version for further development

**Comment by chadlwilson** [comment]
Would be great to get this released. My plugin is now trying to rolling to `0.2.4` which I guess it thinks is the last compatible release... :-/

**Comment by Apoorva-GA** [comment]
@chadlwilson We have added support to intellij 2019.2 in gauge-intellij-plugin nightly with version >= 26/07/19. You can use the nightly until we release.
Please fallow the [instructions](https://github.com/getgauge/Intellij-Plugin#installing-nightly) to install the nightly version.

**Comment by Apoorva-GA** [comment]
@chadlwilson We have released Gauge IntelliJ plugin `0.3.16`. Install the latest version to add support to Intellij 2019.2
