### ISSUE TITLE
Within Intellij 14, plugin causes extra asterisks (`*`) to be inserted.

### ISSUE THREAD

**Issue by dilumr** [getgauge/Intellij-Plugin#39]
See the description in the IntelliJ issue tracker:

[https://youtrack.jetbrains.com/issue/IDEA-136182]
[https://youtrack.jetbrains.com/issue/IDEA-136673]

**Comment by sriv** [comment]
This is strange, Gauge plugin only associates `.spec`, `.cpt` and `.md` filetypes, for editing, and using the `*`.
Need to investigate this further.

Details:
[Plugin.xml](https://github.com/getgauge/Intellij-Plugin/blob/75b545f3b6f051009f2c640a9ccaedc2164854ca/META-INF/plugin.xml#L67) has `fileTypeFactory` as [`SpecFileTypeFactory`](https://github.com/getgauge/Intellij-Plugin/blob/master/src/com/thoughtworks/gauge/language/SpecFileTypeFactory.java#L27)

**Comment by prateekbaheti** [comment]
Its because of a [customEnterHandler](https://github.com/getgauge/Intellij-Plugin/blob/master/src/com/thoughtworks/gauge/GaugeEnterHandler.java) that gauge plugin adds. This is should be resolved on fixing the issue [#37](https://github.com/getgauge/Intellij-Plugin/issues/37)

**Comment by prateekbaheti** [comment]
Fixed in commit [7ee05eb](https://github.com/getgauge/Intellij-Plugin/commit/7ee05eb27386da9a2856ee2b545081a3ad6cb10c)
