### ISSUE TITLE
Unsupported Gauge Version: This version of Gauge Intellij plugin only works with Gauge version >= 0.9.0

### ISSUE THREAD

**Issue by michael-edgar** [getgauge/Intellij-Plugin#392]
I've a gauge project that I've been using since January 2019 and out of nowhere I started getting this unsupported gauge version error. I thought it was due to an update, either in gauge, intellij or the gauge intellij plugin but this seems not to be the case.

I've tried uninstalling and reinstalling gauge, the gauge plugin, intellij, creating a new sample project on my machine and manually specifying the gauge binary path and home. None of these have made any difference. The new sample project has the same issue. However, other machines running the same project seem to have no issue, even on the same version of gauge and intellij. That said, I'm not sure if this would make a difference but I'm running on an Ubuntu machine (18.04) while they were running Windows 10. I've followed the documentation for installing gauge as specified in the following question: Unsupported Gauge Version: This veuge Inrsion of Gatellij plugin only works with Gauge version >= 0.9.0, spec files steps are shown unimplemented

I can still run specs, but some of the functionality of the plugin is no longer available. In particular, where before when running each scenario in a spec was separated into it's own header which had it's own log, now all the scenarios are grouped into one log, often times causing most of the scenario logs to be lost due to the amount of lines in the log.

Edit: I'm running with the following gauge version: Gauge version: 1.0.6, Commit Hash: 2bc49db, html-report (4.0.8), java (0.7.2), screenshot (0.0.1) As for intellij: Intellij IDEA Ultimate 2019.2 Gauge plugin 0.3.16

**Comment by luciferankon** [comment]
@michael-edgar Hey can you just confirm the `Gauge binary path` you can get that in `Preferences->Tools->Gauge`. If this is set to the gauge binary. Can you please provide a screenshot of the same?

**Comment by michael-edgar** [comment]
![gaugePath](https://user-images.githubusercontent.com/22317115/63417099-8c05b200-c3f8-11e9-9bdb-1468c3cd3c17.png)
Here you go @luciferankon

**Comment by luciferankon** [comment]
@michael-edgar Hey could you please elaborate when actually you are getting this particular error? While running or implementing or any other process?

**Comment by michael-edgar** [comment]
@luciferankon I'm getting this error when I am opening any gauge project.

**Comment by Apoorva-GA** [comment]
@michael-edgar  Could you please make sure `Gauge` is installed in the Gauge binary path given in IntelliJ. 
You can run `which gauge`  command to check the same.

**Comment by michael-edgar** [comment]
@Apoorva-GA I've made sure that Gauge is installed in the path specified in the Gauge binary path given in Intellij

**Comment by Apoorva-GA** [comment]
@michael-edgar how did you install gauge? Please make sure Gauge is installed only once(in `/usr/local/bin/`) and not anywhere else. 
You can also try and remove the gauge binary path value and try.

**Comment by michael-edgar** [comment]
I followed the installation guide (https://docs.gauge.org/installation.html) using the Debian installation instructions. I've done some looking and gauge is not installed anywhere else. Specifying or not specifying the binary path does not seem to make a difference

**Comment by negiDharmendra** [comment]
@michael-edgar  There seems to be an issue with the IntelliJ plugin. We will be looking into it as soon as possible. As workaround you can run `gauge telemetry off` and you should not see this issue.

**Comment by kanchan9987** [comment]
I am new to Gauge and facing the same issue. I have installed it on windows:
C:\Program Files\Gauge>gauge --version
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
html-report (4.0.8)
java (0.7.2)
screenshot (0.0.1)


Gaugebinary path : C:/Program Files/Gauge/bin/gauge.exe

Intellij Gauge plugin version : 0.3.16

**Comment by nehashri** [comment]
@kanchan9987 The issues seems to be fixed but a release has not been done yet. Please download the latest nightly plugin from https://plugins.jetbrains.com/plugin/7535-gauge/versions and install it. This may help fix the issue. Refer https://www.jetbrains.com/help/idea/managing-plugins.html for installing plugin archive from disk.

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
Tested version: `2e5182b`
