### ISSUE TITLE
How cat I solve such problem?

### ISSUE THREAD

**Issue by LemonKolbas** [getgauge/Intellij-Plugin#393]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Version information

* IntelliJ version and edition(Community/Ultimate): 
* OS information:
* Gauge IntelliJ plugin version:
* Does the project uses any Build tool(Gradle/Maven)?
```
Run gauge -v on your system and paste the results here
```

**Comment by luciferankon** [comment]
@LemonKolbas We would like to solve your problem. But for that first let us know what is you problem?

**Comment by Apoorva-GA** [comment]
Feel free to reopen with relevant details.
