### ISSUE TITLE
Gauge runner fails with use of closed network connection

### ISSUE THREAD

**Issue by Ashraf407** [getgauge/Intellij-Plugin#394]
Hi Team,

I was facing this issue when ever i am executing the scenario.

Connection to runner with PID 12044 lost. The runner probably quit unexpectedly. Inspect logs for potential reasons. Error : read tcp 127.0.0.154811 ->127.0.0.1:154815: use of closed network connection.

I have done increases the runner time in config.properties.

Kindly help this issue.

Gauge version: 1.0.5
Commit Hash: 562f036

Plugins
-------
html-report (4.0.8)
java (0.7.2)

Thanks,
Ashraf

**Comment by Apoorva-GA** [comment]
@Ashraf407 Could you give us more information like:
-  IntelliJ version and edition
- version of Gauge-IntelliJ plugin 
- OS information

Also does this issue occur when you try to run the specification? Is this specific to running a scenario from IntelliJ?

**Comment by Ashraf407** [comment]
-2018.3.4 and 2019.2(latest) both I have used.
- 0.3.17. nightly- 2019-07-31.
-Windows 7 and Windows 8 both I used.

I was getting executing any scenario of the spec and also executing the any spec file also.

**Comment by Ashraf407** [comment]
Hi Team,
  
 Could  u please help me on that.

Thanks,
Ashraf

**Comment by Ashraf407** [comment]
Thanks Apoorva.. Waiting for good response from your your side.  Kindly let me know if u got any information about this.

Thanks,
Asharf

**Comment by nehashri** [comment]
@Ashraf407 Can try looking at the log files, specifically the `gauge.log` file for any errors reported there. This will help us better debug the issue.

Also, if you can (and don't find any errors), please try to install Gauge 1.0.6 version and also Gauge Java nightly version and see if there are any errors and share the log file if possible. 
You can find the installation instructions in https://github.com/getgauge/gauge-java#nightly-installation.

**Comment by nehashri** [comment]
@Ashraf407 The [gauge-java plugin](https://github.com/getgauge/gauge-java) is for java projects. But if you are using maven as your build tool, you need to use the [gauge maven plugin](https://github.com/getgauge-contrib/gauge-maven-plugin) as well. 

If I understand you correctly, you don't see any errors in any of the log files mentioned above?

**Comment by Ashraf407** [comment]
Still issue not got resolved .
I have done offline plugin installation which u have sent before 2 nd link while using the  .zip files.

**Comment by Ashraf407** [comment]
I have done wt ever u guys are said but still in my gauge.log is failed some plugin
I have download offline plugins.

Failed to download 
html-report-install.json.
Java-install.json.

**Comment by zabil** [comment]
Gauge requires will require offline installation of the following plugins
* [Gauge html report](https://github.com/getgauge/html-report/releases)
* [Gauge screenshot](https://github.com/getgauge/gauge_screenshot/releases)
* [Gauge java](https://github.com/getgauge/gauge-java/releases)

Please follow the links above to download the right archive for your os and use the [offline installation commands](https://manpage.gauge.org/gauge_install.html) to install it.

**Comment by Ashraf407** [comment]
Offline installation i have done but in log files it was showing same failed to download plugins which I mentioned above messages.
U have given correct answers but something is wrong from my side only I will try my level best but finally failed to implement this framework in my project .

**Comment by Ashraf407** [comment]
Hi Team,

In my gauge.log file it was showing.
Plugin java already installed.
Plugin html-report is already installed

But again it was showing 
installing required plugins 
Downloading https://downloads.gauge.org/plugins...

Failed to download screenshot-install.json
Downloading https://downloads.gauge.org/plugins...
Failed to download html-report-install.json

Same like as jav-install.json.
Please help me I have reached near i thoght.

Thanks,
Ashraf

**Comment by Ashraf407** [comment]
@ zabil 
@Nehashri
@Apoorva

Please help me.

**Comment by apoorvab** [comment]
Tagging the Apoorva that can help. @Apoorva-GA

**Comment by Ashraf407** [comment]
@Appoorva-GA 
Waiting for Ur reply.

**Comment by Debashis9012** [comment]
> Plugin java already installed.
> Plugin html-report is already installed

@Ashraf407 what about screenshot plugin? I don't see any log regarding screenshot plugin has been installed like java and html-report. As screenshot is a mandatory plugin so please make sure you have installed screenshot plugin as @zabil mentioned earlier.

You are getting the below issue due to lack of internet connectivity.

```
installing required plugins
Downloading https://downloads.gauge.org/plugins...

Failed to download screenshot-install.json
Downloading https://downloads.gauge.org/plugins...
Failed to download html-report-install.json
```

I would suggest please check your internet connectivity. If you are under any secure network you can set up proxy setting by following [HTTP_Proxy](https://docs.gauge.org/configuration.html?os=macos&language=javascript&ide=vscode#http-proxy-setting-while-using-gauge)

**Comment by Ashraf407** [comment]
Where I need to configure this proxy settings in intellj .

File > settings > Http Proxy .
Correct?

**Comment by nehashri** [comment]
@Ashraf407 As suggested by @Debashis9012, you need to set this variable in your system's environment variables. Please look at the documentation https://docs.gauge.org/configuration.html#http-proxy-setting-while-using-gauge

**Comment by Ashraf407** [comment]
Please find this below image is correct for setting the proxy.
![Details](https://user-images.githubusercontent.com/47331019/66951934-60760100-f010-11e9-93db-43933b052318.PNG)

**Comment by Ashraf407** [comment]
@Debashis9012 , please check whether if it is correct or not.

**Comment by negiDharmendra** [comment]
@Ashraf407 It should be fine.

**Comment by Ashraf407** [comment]
Thanks Dharmendra.
