### ISSUE TITLE
Connection runner time out

### ISSUE THREAD

**Issue by KVenkatR813** [getgauge/Intellij-Plugin#403]
Hi Team, 

I am facing this issue frequently. 

Some times my specs are executing fine some time I was facing this issue. 

I am using Maven gauge project. All plugins I have provided correctly. 

 "Connection to runner with pid 6420. The runner probably quit unexpectedly. Inspect log for potential reasons. Error : read tcp 127.0.0.1:149458->127.0.0.1:49459: use of closed network connection"

**Comment by Debashis9012** [comment]
@KVenkatR813 Could you please share OS, gauge and plugins version information?

**Comment by KVenkatR813** [comment]
Gauge version :1.0.5
html-report:4.0.8
Java:0.7.2
OS:Win 7

**Comment by KVenkatR813** [comment]
Could you please help me to resolve the above issue facing

**Comment by negiDharmendra** [comment]
@KVenkatR813 Is it possible for you to switch to Windows 10.

**Comment by KVenkatR813** [comment]
Organisation supports only win7 here, not passible to switch to win10, mean this gauge framework will not support win7?
Kindly clarify me

**Comment by Ashraf407** [comment]
@Apoorva-GA,. I am also using windows 7 because of that  facing same issue on that will it be possible to resolve because most of the company still they are using windows 7 .
