### ISSUE TITLE
Environment variables are not picked up by the plugin

### ISSUE THREAD

**Issue by haroon-sheikh** [getgauge/Intellij-Plugin#404]
### Expected behavior
environment variable is picked up.

### Actual behavior
Environment variables are not picked up by the plugin

```bash
Error ----------------------------------
			
[Gauge]
'MY_VAR' env variable was not set
			
Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://gitter.im/getgauge/chat
			
Your Environment Information -----------
	darwin, 1.0.6
	flash (0.0.1), html-report (4.0.8), java (0.7.2), js (2.3.5), reportserver (0.1.1), screenshot (0.0.1), spectacle (0.1.3), xml-report (0.2.1)
```

### Steps to reproduce
1. Set environment variable `MY_VAR=my_value`
2. Reference the variable in default.properties `my_property=${MY_VAR}`
3. Import/reopen the project in IntelliJ.
3. The value of ${MY_VAR} should be assigned to `my_property` 

### Version information

* Does the project uses any Build tool(Gradle/Maven)? Maven
```
* Idea version: 2019.2.3
* API version: IU-192.6817.14
* Plugin version: 0.3.17.nightly-2019-07-31
* Gauge version: 1.0.6
```

**Comment by negiDharmendra** [comment]
@haroon-sheikh How are you setting the env variable?

If you are setting this env from terminal then make sure you start the IntelliJ from the same terminal. Other wise IntelliJ will note pickup the env variable.

**Comment by haroon-sheikh** [comment]
@negiDharmendra I'm starting it from the same terminal. I've also set the env variables in bash_profile and bashrc but it still does not pick it up.

**Comment by negiDharmendra** [comment]
@haroon-sheikh The problem with the IntelliJ is that it does not inherit the env from .bash_profile and .bashrc
You will have export them on the terminal and then start the IntelliJ from the same terminal session.

**Comment by haroon-sheikh** [comment]
Ok. so there's no way to tell gauge plugin to include params?
Just out of interest, why does it try to load the env file on import? should it not only do that at runtime?

**Comment by negiDharmendra** [comment]
> why does it try to load the env file on import

You mean when we import the project in IntelliJ

**Comment by haroon-sheikh** [comment]
Yep, why does it do that on importing the project?

**Comment by negiDharmendra** [comment]
IntelliJ plugin tries to start Gauge API service as soon as Gauge project is imported in IntelliJ. Which is why Gauge fails as it does not find the required ENV variable.

**Comment by haroon-sheikh** [comment]
Is there something we can do so that it wouldn't error?

**Comment by negiDharmendra** [comment]
I am afraid to say but the only workaround is to launch the IntelliJ from the terminal where required environment variables are available.
