### ISSUE TITLE
Gauge API not started

### ISSUE THREAD

**Issue by eyupco** [getgauge/Intellij-Plugin#411]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Version information

* IntelliJ version and edition(Community/Ultimate): 
* OS information:
* Gauge IntelliJ plugin version:
* Does the project uses any Build tool(Gradle/Maven)?
```
Run gauge -v on your system and paste the results here
```

**Comment by nehashri** [comment]
@eyupco please give more information on the error you are facing.

**Comment by eyupco** [comment]
sorry for the issue. we solved the problem with local admin
