### ISSUE TITLE
Bug unknown flag: --daemonize

### ISSUE THREAD

**Issue by brobles82** [getgauge/Intellij-Plugin#415]
### Expected behavior
After install the plugin for IntelliJ and the java version should work as expected

### Actual behavior
You can not run any step and unknown error appears

After install the plugin all the steps are red and this error is logged

`Error: unknown flag: --daemonize`

### Steps to reproduce
1. Install intellj
2. Install gauge
3. Install java
4. Load a java project

### Version information

* IntelliJ version and edition(Community/Ultimate): Ultimate 2019
* OS information: Catalina
* Gauge IntelliJ plugin version: 0.2.4
* Does the project uses any Build tool(Gradle/Maven)? Maven

```
Gauge version: 1.0.6

Plugins
-------
java (0.7.3)
```

**Comment by negiDharmendra** [comment]
@brobles82 Please update Gauge Intellij to [latest version ](https://github.com/getgauge/Intellij-Plugin/releases/tag/v0.3.18)

**Comment by brobles82** [comment]
Now It's working with the last version thx!
