### ISSUE TITLE
Intellij gauge pluggin

### ISSUE THREAD

**Issue by catamesac** [getgauge/Intellij-Plugin#417]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Version information

* IntelliJ version and edition(Community/Ultimate): 
* OS information:
* Gauge IntelliJ plugin version:
* Does the project uses any Build tool(Gradle/Maven)?
```
Run gauge -v on your system and paste the results here
```

**Comment by negiDharmendra** [comment]
@catamesac Please tell us what issue you are facing with Intellij-Plugin

**Comment by catamesac** [comment]
Intellij doesn't recognize the steps in gauge.. .spec file. It is in the lasts version

Enviado desde Yahoo Mail para Android 
 
  El mar., 3 de dic. de 2019 a la(s) 4:23 a. m., Dharmendra Singh<notifications@github.com> escribió:   
@catamesac Please tell us what issue you are facing with Intellij-Plugin

**Comment by negiDharmendra** [comment]
@catamesac We will require few information from you to investigate this issue.

- run `gauge -v` on your terminal and share the output with us
- which os your working on
- java version
- Intellij version and Gauge Intellij Plugin version.
- Were you able to replicate this issue with a new Gauge Java project. If not is it possible for you to share the sample project.

**Comment by catamesac** [comment]
I'm sorry but I'm not able to share it because is my work project, but the issue is with 
Intellij version and Gauge Intellij Plugin version.. when I try to run the spec intellij it doesn't recognize the steps and ask for there implementation
Enviado desde Yahoo Mail para Android 
 
  El mar., 3 de dic. de 2019 a la(s) 6:51 a. m., Dharmendra Singh<notifications@github.com> escribió:   
@catamesac We will require few information from you to investigate this issue.
   
   - run gauge -v on your terminal and share the output with us
   - which os your working on
   - java version
   - Intellij version and Gauge Intellij Plugin version.
   - Were you able to replicate this issue with a new Gauge Java project. If not is it possible for you to share the sample project.

**Comment by negiDharmendra** [comment]
@catamesac Which versions of Intellij and Gauge Intellj plugin you are on?

**Comment by catamesac** [comment]
And I know is the last version because I download the version before and is working

Enviado desde Yahoo Mail para Android 
 
  El mar., 3 de dic. de 2019 a la(s) 6:51 a. m., Dharmendra Singh<notifications@github.com> escribió:   
@catamesac We will require few information from you to investigate this issue.
   
   - run gauge -v on your terminal and share the output with us
   - which os your working on
   - java version
   - Intellij version and Gauge Intellij Plugin version.
   - Were you able to replicate this issue with a new Gauge Java project. If not is it possible for you to share the sample project.

**Comment by negiDharmendra** [comment]
@catamesac Do you see any error in Intellij when you open the Gauge project? If yes, can you share the error message.

**Comment by catamesac** [comment]
I'm already checking and Gause has a new release and I have gauge 0.3.18 and intellij I have 2019.2 .. the issue is in the 2019.2 version 

Enviado desde Yahoo Mail para Android 
 
  El mar., 3 de dic. de 2019 a la(s) 7:18 a. m., Dharmendra Singh<notifications@github.com> escribió:   
@catamesac Which versions of Intellij and Gauge Intellj plugin you are on?

**Comment by negiDharmendra** [comment]
**My setup:**
Gauge Intellij Version : 0.3.18
Intellij version 
  ```
IntelliJ IDEA 2019.2.4 (Ultimate Edition)
Build #IU-192.7142.36, built on October 29, 2019

Runtime version: 11.0.4+10-b304.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: 
Non-Bundled Plugins: com.thoughtworks.gauge, net.seesharpsoft.intellij.plugins.csv, org.asciidoctor.intellij.asciidoc, org.github.erikzielke.gotoproject, BashSupport, org.jetbrains.plugins.go, Pythonid, org.jetbrains.plugins.ruby, training
```

For me every thing works fine.

**Comment by nehashri** [comment]
@catamesac Can you atleast run `gauge -v` on your command prompt and paste its contents here? It is very hard for us to debug this issue without more information

**Comment by negiDharmendra** [comment]
@catamesac Any updates?

**Comment by catamesac** [comment]
Everything is working good now.. thanks 

Enviado desde Yahoo Mail para Android 
 
  El mar., 14 de ene. de 2020 a la(s) 3:29 a. m., Dharmendra Singh<notifications@github.com> escribió:   
@catamesac Any updates?
