### ISSUE TITLE
Not able to find the step implemented

### ISSUE THREAD

**Issue by iamsuv** [getgauge/Intellij-Plugin#419]
### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Version information

* IntelliJ version and edition(Community/Ultimate): 
* OS information:
* Gauge IntelliJ plugin version:
* Does the project uses any Build tool(Gradle/Maven)?
```
Run gauge -v on your system and paste the results here
```

**Comment by negiDharmendra** [comment]
@iamsuv  We will require few information from you to investigate this issue.

- run `gauge -v` on your terminal and share the output with us
- which os your working on
- java version
- Intellij version and Gauge Intellij Plugin version.
- Were you able to replicate this issue with a new Gauge Java project. If not is it possible for you to share the sample project.

**Comment by nehashri** [comment]
please feel free to reopen the issue with more information
