### ISSUE TITLE
CPU usage is very high during debugging

### ISSUE THREAD

**Issue by vmatyusGitHub** [getgauge/Intellij-Plugin#421]
### Expected behavior
During debugging a spec I would expect that the CPU usage remain acceptable.

### Actual behavior
During debugging a spec the CPU usage goes up to 300 percent or even higher. And after the stop of the debugging the CPU usage remains at 120%. I always need to kill IntelliJ to prevent the computer from heat up.

### Steps to reproduce
1. Start to debug a spec with IntelliJ
2. Stop at a breakpoint and after some seconds the CPU usage goes up to 300% or even higher
3.

### Version information

* IntelliJ Community 2019.2.1
* macOS Catalina 10.15.1 
* Gauge IntelliJ plugin version: 0.3.18
* Does the project uses any Build tool(Gradle/Maven)? Gradle
```
Gauge version: 1.0.6

Plugins
-------
html-report (4.0.8)
java (0.7.2)
js (2.3.5)
python (0.3.5)
screenshot (0.0.1)
xml-report (0.2.2)
Veronika-MBP:java veronika$ 

```
I would like to request your help because it is very disturbing.

**Comment by nehashri** [comment]
@vmatyusGitHub We will look at fixing this issue. 
In the meanwhile you can try using[ Visual Studio Code Gauge plugin](https://marketplace.visualstudio.com/items?itemName=getgauge.gauge) with [Visual Studio Code](https://code.visualstudio.com/) as we will be [deprecating support for IntelliJ in Oct 2020](https://github.com/getgauge/Intellij-Plugin#deprecation-notice).

**Comment by nehashri** [comment]
@vmatyusGitHub The issue may also be related to IntelliJ's issue https://youtrack.jetbrains.com/issue/IDEA-221203. Can you try upgrading your version of IntelliJ as mentioned in the issue?

**Comment by vmatyusGitHub** [comment]
I just upgraded the IntelliJ to 2019.3
And I tried out the debugging and now I am not encountering constant load on the CPU.
It goes up to 115% but just for temporary, after starts to drop down.
For me this operation acceptable now. Thank you for your help!
