### ISSUE TITLE
Incompatible with IDEA 2020.1 EAP

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/Intellij-Plugin#423]
The Gauge plugin is reported as incompatible with IDEA 2020.1 EAP. The interface recommends downgrading to 0.2.4, but I suspect this would not be advised because it does not work with the most recent versio of Gauge.

![image](https://user-images.githubusercontent.com/6200170/73078427-c384f880-3e87-11ea-8ef3-d86ab9cf0017.png)

### Version information

* IntelliJ version and edition(Community/Ultimate):  `IntelliJ IDEA 2020.1 EAP (Ultimate Edition), Build #IU-201.3803.71`
* OS information: Windows 10 1909
* Gauge IntelliJ plugin version: 0.3.18

**Comment by BugDiver** [comment]
@Thunderforge We will try to add support for IDEA 2020 as soon as possible.

FYI we have deprecated the IntelliJ-plugin, so there will not any active development for it.

https://github.com/getgauge/Intellij-Plugin#deprecation-notice

**Comment by BugDiver** [comment]
@Thunderforge I tried to make the plugin compatible with IDEA 2020 but it won't be possible unless JetBrains releases the IDEA package for version 2020.
Currently, they haven't released the required dependencies for 2020.

**Comment by Thunderforge** [comment]
@BugDiver What about targeting `201-EAP-SNAPSHOT` (see the [snapshots repository](https://www.jetbrains.com/intellij-repository/snapshots/)). Would that work? That would add support for the EAP versions, right?

**Comment by BugDiver** [comment]
@Thunderforge That should work. But I think releasing the plugin with a snapshot dependency would be good.

Can you please try to build from source with snapshot dependency? 
Also please let us know if that works for you.

**Comment by Thunderforge** [comment]
@BugDiver Created #426. I'm not entirely sure how to test it aside from installing the plugin locally and seeing if I can load a project for it. The big issue was that the plugin was using some deprecated stuff, so I had to replace that.
