### ISSUE TITLE
Relicense plugin under Apache 2?

### ISSUE THREAD

**Issue by yole** [getgauge/Intellij-Plugin#434]
Given that the plugin is being deprecated, JetBrains is considering taking over the maintenance of the plugin. For us, it would be far easier to take over the plugin if it was licensed under Apache 2 rather than GPLv3. The current license effectively does not allow us to keep the code in our monorepo and does not allow us to bundle the plugin into the distributions of our products. We could continue maintaining the plugin in a separate repository and releasing it separately from our IDEs, but this would require considerably more effort and would be less attractive.

If the plugin is relicensed, we'll keep it evolving in the open (the code will be available under https://github.com/jetbrains/intellij-plugins).

**Comment by zabil** [comment]
Thanks @yole!

This is something we can do. I will get back to you soon on this as I need to check a few things before changing the license.

**Comment by zabil** [comment]
@Thunderforge @haroon-sheikh 

Can both of you please indicate your approval as a comment on this issue?

**Comment by haroon-sheikh** [comment]
I'm happy with this. 👍

**Comment by Thunderforge** [comment]
I grant my permission to relicense my contributions under Apache 2 (as well as future versions and equivalent licenses).

**Comment by zabil** [comment]
@yole source code is now Apache License Version 2.0. Cheers.

**Comment by yole** [comment]
Thanks a lot!

**Comment by zabil** [comment]
@yole circling back on this. Is there anything else you need to get started with the process?
