### ISSUE TITLE
JetBrains take over

### ISSUE THREAD

**Issue by sirinath** [getgauge/Intellij-Plugin#443]
As per https://github.com/getgauge/Intellij-Plugin/issues/434 has JetBrains take over as yet. If so it might be an idea to remove the deprecation notice.

Is the JetBrains maintained version maintained in another repository? What is the roadmap?

cc: @yole

**Comment by zabil** [comment]
Also refer https://github.com/getgauge/Intellij-Plugin/issues/442#issuecomment-665816284

**Comment by jreznot** [comment]
@zabil We are preparing sources for 2020.2 release and the only thing that we need to know: Should we release a new plugin or continue releasing it to the same plugin in the JetBrains marketplace?

The plugin sources will be available in https://github.com/JetBrains/intellij-plugins repository under Apache 2 License as decided before. It will be available for IntelliJ IDEA Community Edition as the original plugin.

**Comment by zabil** [comment]
> continue releasing new versions to the same plugin in the JetBrains marketplace

If it's ok, we prefer this so that users won't have to install another plugin and can easily upgrade.

> The plugin sources will be available in https://github.com/JetBrains/intellij-plugins repository under Apache 2 License as decided before. It will be available for IntelliJ IDEA Community Edition as the original plugin.

Yes, this is works, when the new repo is up we can archive this repo and refer to that.

**Comment by jreznot** [comment]
@zabil Then, could you please add Yuriy Artamonov (yuriy.artamonov at jetbrains com) as a plugin author so I could setup publishing and to confirm that the team is OK with the new versions from the JetBrains repository.

**Comment by sriv** [comment]
@jreznot - I just added you as a developer to https://plugins.jetbrains.com/plugin/7535-gauge

Please check and let us know if there's any other place that you'd like access to.

**Comment by zabil** [comment]
There's a new release out! at https://plugins.jetbrains.com/plugin/7535-gauge 

A big shout out and thanks to JetBrains @jreznot

**Comment by jreznot** [comment]
Finally, sources has landed to https://github.com/JetBrains/intellij-plugins/tree/master/gauge 
We still in progress of setting CI for 2020.2, but I've released a version compatible with it and users may update.
New versions will only be compatible with the corresponding IntelliJ IDEA release lines, so old ones will be used for 2020.1 and earlier versions.

Please do not remove this repository, may be just archive it.

**Comment by jreznot** [comment]
And it would be great to update the deprecation warning with the link to the new repository.
Users can create issues right in https://youtrack.jetbrains.com/issues/IDEA

**Comment by zabil** [comment]
I've updated the README. Will be archiving the repo now.
