### ISSUE TITLE
Plugin not compatible with version 2020.2

### ISSUE THREAD

**Issue by cyberjaime45** [getgauge/Intellij-Plugin#444]
IntelliJ IDEA 2020.2 (Community Edition)
Build #IC-202.6397.94, built on July 27, 2020
Runtime version: 11.0.7+10-b944.20 x86_64

**Comment by zabil** [comment]
Please try version 0.4 https://plugins.jetbrains.com/plugin/7535-gauge this plugin is now maintained by JetBrains
