### ISSUE TITLE
find usages action does not work on unimplemented steps

### ISSUE THREAD

**Issue by kashishm** [getgauge/Intellij-Plugin#46]
It works only if the cursor is before the step identifier(*) otherwise it shows an error message.

Example : 
![screen shot 2015-03-16 at 5 31 58 pm](https://cloud.githubusercontent.com/assets/5915802/6665684/6a5c6236-cc02-11e4-8ad8-d4d18bf1af78.png)

Correct behaviour: Find usages should work irrespective of the cursor position on step

**Comment by sriv** [comment]
Closing as stale. Please comment/reopen if this is still valid.
