### ISSUE TITLE
Gauge plugin ignores local scope passed to reference search which results in IDE freezes

### ISSUE THREAD

**Issue by donnerpeter** [getgauge/Intellij-Plugin#53]
See https://youtrack.jetbrains.com/issue/IDEA-137990

![screenshot from 2015-03-23 12 31 03](https://cloud.githubusercontent.com/assets/122009/6779071/881e648a-d158-11e4-9e83-94702f24c65d.png)

**Comment by tonymwinters** [comment]
+1 Happens ALL the time

**Comment by sriv** [comment]
Related: https://github.com/getgauge/Intellij-Plugin/issues/51

**Comment by kashishm** [comment]
Released a new version which disables find usages feature temporarily.

**Comment by kashishm** [comment]
fixed in latest release ([0.0.12](https://github.com/getgauge/Intellij-Plugin/releases/tag/v0.0.12))
