### ISSUE TITLE
Step Implementation auto-complete error(IntelliJ)

### ISSUE THREAD

**Issue by anishvenkat** [getgauge/Intellij-Plugin#55]
Hi Team,

I was trying to create a step and then when I tried to use it with the help of Auto-complete, it doesn't show up. Please find the steps below to replicate the behaviour:

Steps:

1. Create a new step. For ex: Login 
2. Now create the step implementation and when you reach the method implementation page, just refactor your step to 'Login with <username> and <password>'. 
3. Now after you save the Method implementation page and come back to the Test page to implement it, it doesn't show up in the Auto-complete.

Please do the needful.

Regards,
Anish

**Comment by mahendrakariya** [comment]
Not reproducible.
