### ISSUE TITLE
Gauge API does not start for Gauge modules nested inside an Intellij project 

### ISSUE THREAD

**Issue by ApoorvaM** [getgauge/Intellij-Plugin#64]
* For nested projects, gauge is started in daemon in the top level project which fails since there is a daemon running already on that port. This should start in the new module.
* project-lib and gauge-lib are not added as dependencies to the new module added.

As a result, the steps inside the new module added might get marked as unimplemented.

**Comment by prateekbaheti** [comment]
Fixed in [commit](https://github.com/getgauge/Intellij-Plugin/commit/443cbc0b231a6d7a0cba1c9af1a1f5b24e7c12e0)
