### ISSUE TITLE
Gauge project initialisation progress bar does not show up for Intellij Community Edition

### ISSUE THREAD

**Issue by prateekbaheti** [getgauge/Intellij-Plugin#66]
The progress bar which indicates that project initialization may take a few minutes does not appear in Community edition of Intellij. The progress bar is visible usually if the gauge java plugin is not installed, otherwise it quickly disappears as project initialization is fast.

![project_init](https://cloud.githubusercontent.com/assets/1955832/7627693/850f6052-fa37-11e4-85d6-1ca9ec0d235c.png)

**Comment by sriv** [comment]
Closing as stale. Please comment/reopen if this is still valid.
