### ISSUE TITLE
Autocomplete removes a line when pressing tab on the autocomplete option

### ISSUE THREAD

**Issue by prateekbaheti** [getgauge/Intellij-Plugin#68]
Steps to reproduce:
* A step ```Say "hello" to "gauge"``` exists project
* Enter ```* Say``` and autocomplete ( press ctrl/cmd + space)
* Press tab on the ```Say <greeting> to <name>``` option

The newline character at the end of the line is deleted.

**Comment by mahendrakariya** [comment]
Posted question on IntelliJ forums.
https://devnet.jetbrains.com/thread/466598?tstart=0
