### ISSUE TITLE
Table formatting doesn't work

### ISSUE THREAD

**Issue by deepthigc** [getgauge/Intellij-Plugin#85]
Confirm if this is a linux specific, it seems to work on a regular windows/mac + intellij env.

**Comment by mahendrakariya** [comment]
Not working on mac as well.

**Comment by kashishm** [comment]
The keyboard shortcut `ctrl + alt + shift + l` is conflicting with some other actions on IntelliJ. This is not consistent across all IntelliJ versions.

**Workaround:** User can do `ctrl + shift + a` and select `spec format` action. Alternatively user has the ability to change the keyboard shortcuts.
