### ISSUE TITLE
new file gets created in resources folder instead of test folder by default

### ISSUE THREAD

**Issue by deepthigc** [getgauge/Intellij-Plugin#89]
**Steps to reproduce**

* Add a new step to spec file.
* Press alt+enter. Select create implementation in new file

**Comment by mahendrakariya** [comment]
This issue is not reproducible on Mac. But it can be reproduced on Windows and Ubuntu.
Have posted a [question](https://devnet.jetbrains.com/message/5550283#5550283) on IntelliJ forums to figure out what should we do differently.
