### ISSUE TITLE
inconvenient display in RUN drop down list

### ISSUE THREAD

**Issue by uzmar** [getgauge/Intellij-Plugin#96]
whenever run spec ,it adds a number along with spec. that looks very confusing when run spec.
it confuses user to which spec needs to be executed.
Run->run

<img width="464" alt="screen shot 2015-09-10 at 8 56 18 am" src="https://cloud.githubusercontent.com/assets/10433272/9780278/7ef70c9a-57a4-11e5-9dbd-1d1b67bd4139.png">

**Comment by mahendrakariya** [comment]
This is default IntelliJ behavior. You can customize it by editing run configurations.
