### ISSUE TITLE
"In Parallel" should be a checkbox, not a radio button

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/Intellij-Plugin#97]
The setting to turn on parallelization in the Run/Debug Configurations appears as a [radio button](https://en.wikipedia.org/wiki/Radio_button):

![image](https://cloud.githubusercontent.com/assets/6200170/9797667/0eaffb36-57c2-11e5-8b4f-9bb8a1fa00be.png)

Radio buttons are designed to be for options that have two or more mutually exclusive choices displayed on a screen, which is not what is happening here. Instead, it ought to be a [checkbox](https://en.wikipedia.org/wiki/Checkbox), which is more appropriate for a choice that is either on or off.

**Comment by BugDiver** [comment]
@sguptatw This should be available in nightly build > 2016-04-29
